{
  "hash": "a6cc04f29e04d4cd74f1eb8f798311be",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Penyakit Graves pada seorang perempuan dengan Sistemik Lupus Eritematosus\nauthors:\n  - name: dr. Kadek Adit Wiryadana\n    affiliation: Universitas Udayana\n    roles: writing\n    corresponding: true\n  - name: dr. I Made Siswadi Semadi, M.Biomed, SpPD, K-EMD\n    affiliation: Universitas Udayana\n    roles: writing\n    corresponding: false\n  - name: dr. Pande Ketut Kurniari, SpPD, K-R\n    affiliation: Universitas Udayana\n    roles: writing\n    corresponding: false\nbibliography: references.bib\ncsl: wiryadana.csl\n---\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(\"tidyverse\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.0\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ purrr::%||%()   masks base::%||%()\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(\"googlesheets4\")\nlibrary(\"ggplot2\")\nlibrary(\"dplyr\")\nlibrary(\"hrbrthemes\")\nlibrary(\"googlesheets4\")\nlibrary(\"patchwork\")\n```\n:::\n\n\n\n## Abstract\n\n**keywords**:\n\n## Pendahuluan\n\nKoinsidensi penyakit Graves dan sistemik lupus eritematosus (SLE) belakangan ini mendapat perhatian lebih karena ditemukan memiliki hubungan yang tidak sekedar sesuatu yang terjadi secara acak. Hubungan kausal antara kedua entitas penyakit automimun tersebut masih belum banyak diketahui dan saat ini masih terdapat berbagai penelitian yang mendalami hal tersebut.[@xian2024] Penyakit Graves merupakan salah satu penyakit autoimun pada organ endokrin tiroid dan merupakan penyebab utama hipertiroidisme.[@smith2016] Insiden enyakit Graves sebagai penyakit autoimun termasuk cukup tinggi dengan rentang 20 - 50 kasus per 100.000 individual serta tingkat prevalensi diperkirakan 1 - 1.5%.[@davies2020] Penyakit Graves memilki target organ khusus, namun koinsidensi dengan penyakit autoimun lain seperti SLE, rheumatoid arthritis, multipel sklerosis, diabetes tipe 1 dan lainnya diperkirakan sekitar 16,7% dari total pasien dengan penyakit Graves. Data lebih lanjut dari laporan serial kasus terbaru juga menunjukan bahwa persentase pasien dengan penyakit Graves juga ditemukan memiliki 3 penyakit autoimun lain sebesar 1.5%.[@ferrari2019]\n\nSLE merupakan penyakit yang memiliki variasi spektrum klinis yang luas akibat terget organ penyakit yang multipel dan heterogen. Penelitian kohort multisenter di China menemukan bahwa individu dengan penyakit Graves lebih rentan mengalami SLE dibanding individu kontrol yang sehat.[@lee2020] Penelitian terbaru dari Xian et al dengan analisis randomisasi mendelian menemukan bahwa terdapat korelasi antara penyakit Graves dengan SLE, dan masing-masing entitas autoimun tersebut saling mendukung untuk koinsidensi autoimun lainnya. Beberapa temuan ini memberikan gambaran bahwa pada praktik klinis diharapkan klinisi dapat meningkatkan skrining penyakit autoimun khususnya penyakit Graves atau SLE saat menegakan diagnosis salah satu penyakit autoimun tersebut.[@xian2024] Laporan kasus ini memaparkan seorang pasien perempuan dengan krisis tiroid akibat penyakit Graves yang terlebih dahulu mengalami atrial fibrilasi dan baru terdiagnosis SLE.\n\n## Laporan Kasus\n\nSeorang perempuan (23066258) usia 23 tahun datang ke instalasi gawat darurat dirujuk dengan keluhan utama dada berdebar sejak 1 hari sebelum masuk rumah sakit perujuk. Selain dada berdebar, pasien mengeluh mual dan pusing sejak 1 bulan sebelumya disertai rambut rontok, ruam kemerahan pada pipi serta nyeri pada persendian kedua kaki yang muncul hilang timbul sejak 1 minggu sebelumnya. Pasien mengalami diare berulang sejak 2 bulan terakhir, serta diare terakhir mulai 4 hari sebelum masuk rumah sakit. Diare konsistensi feses lunak hingga cair, tanpa darah dan tidak disertai nyeri perut. Pasien mengalami penurunan berat badan 10 kg dalam kurun waktu 6 bulan terakhir. Riwayat demam lama dan kencing berbuih disangkal. Menstruasi pasien dikatakan tidak teratur dan menstruasi terakhir 6 bulan sebelum masuk rumah sakit. Pasien belum menikah dan menyangkal adanya riwayat berhubungan seksual.\n\nRiwayat penyakit kronis seperti diabetes, penyakit jantung, penyakit ginjal disangkal. Pasien memiliki riwayat nyeri hilang timbul pada ulu hati sejak kecil yang membaik dengan membeli obat secara mandiri. Riwayat nyeri tenggorokan dikatakan pada 6 bulan sebelumnya namun hanya kurang dari 1 minggu dan telah mendapatkan pengobatan dari dokter THT. Pasien sebelum rawat inap tidak dalam pengobatan rutin, namun pada rumah sakit perujuk pasien telah mendapatkan perawatan selama 4 hari namun tidak membaik dengan diagnosis suspek SLE, anemia sedang, kardiomiopati lupus, atrial flutter dan observasi nodul hepar. Saat dirujuk pasien mendapatkan terapi drip KCL 50 meq, seftriakson 1 gram tiap 12 jam intravena, metilprednisolon 125 mg tiap 12 jam intravena, parasetamol 650 mg tiap 8 jam per oral, Kalium Slow Release 600 mg tiap 8 jam per oral, bisoprolol 2.5 mg tiap 24 jam per oral, ramipril 5 mg tiap 24 jam per oral. Sebelum sakit memberat, pasien menjalani kuliah di malang kemudian 1 minggu sebelum masuk rumah sakit pasien mengunjungi keluarganya di Denpasar.\n\nSaat di IGD pasien dalam kondisi compos mentis, tekanan darah 130/90 mmHg, denyut nadi 128 kali/menit dengan irama iregular dan kuat angkat, laju respirasi 24 kali/menit, saturasi oksigen 99% dengan udara ruangan dan suhu aksila 36.6 C. Pasien tampak sakit berat dan malnutrisi (tinggi badan 155 cm, berat badan terakhir 34 kg, IMT 14.5 kg/m^2^, lingkar lengan atas 18 cm). Temuan signifikan pada pemeriksaan fisik meliputi sklera ikterus, ruam malar, kardiomegali, bilateral pedal edema dan makula hiperemis tersebar pada beberapa bagian tubuh (gambar [-@fig-fotoklinis]). Pada pasien tidak ditemukan adanya organomegali maupun efusi sendi.\n\n::: {#fig-fotoklinis layout-nrow=\"3\"}\n![Ruam pada belakang telinga kiri](/image/klinis/heldi_leherbelakangkiri.jpg){#fig-blkgkiri}\n\n![Foto klinis wajah](/image/klinis/heldi_wajahdepan.jpg){#fig-wajah}\n\n![Ruam pada belakang telinga kanan](/image/klinis/heldi_fotoleherbelakangkanan.jpg){#fig-blkgkanan}\n\n![Foto klinis leher kanan](/image/klinis/haim_leherkanan.jpg){#fig-leherkanan}\n\n![Foto klinis leher depan](/image/klinis/heldi_leherdepan.jpg){#fig-leherdepan}\n\n![Foto klinis leher kiri](/image/klinis/heldi_leherkiri.jpg){#fig-leherkiri}\n\n![Foto klinis kedua tangan](/image/klinis/haim_keduatangan.jpg){#fig-tangan}\n\n![Sklera ikterik](/image/klinis/heldi_mata.jpg){#fig-mata}\n\n![Foto klinis kedua kaki](/image/klinis/haim_keduakaki.jpg){#fig-kaki}\n\nFoto klinis pasien tampak sklera ikterik, ruam malar disertai makula eritema pada beberapa bagian tubuh.\n:::\n\nPada evaluasi data saat di IGD pasien memiliki skor kriteria klasifikasi SLE dari American College of Rheumatology (ACR)/European League Against Rheumatism (EULAR) 20 poin, dengan rincian lupus kutan akut (+6), keterlibatan sendi (+6), proteinuria (+4) dan thrombositopenia (+4). Pada saat presentasi, pasien menunjukan gejala sesuai dengan SLE aktivitas berat berdasarkan kriteria MEX SLEDAI (tabel [-@tbl-mexsledai])\n\n| MEX SLEDAI       | 7/11/2023 |\n|------------------|-----------|\n| Proteinuria      | +6        |\n| Hemolisis        | +3        |\n| Thrombositopenia | +3        |\n| Arthrtis         | +2        |\n| Ruam Malar       | +2        |\n| Total            | 16        |\n\n: Skor MEX-SLEDAI saat pemeriksaan di instalasi gawat darurat {#tbl-mexsledai}\n\nPada pemeriksaan penunjang ditemukan beberapa kelainan. Pemeriksaan darah lengkap ditemukan anemia sedang normokromik normositer dan trombositopenia. Pada pemeriksaan kimia klinik ditemukan peningkatan *Serum Glutamic Oxaloacetic Transaminase* (SGOT), hipoalbuminemia, hipokalemia, alkalosis metabolik (tabel [-@tbl-dl; -@tbl-kimia]). Pada pemeriksaan foto thorax anteroposterior tak tampak kelainan pada pulmonum. Pada jantung terukur *Cardiothoracic Ratio* (CTR) 66 %, dengan *splaying carina*, apeks mendatar, pinggang jantung melurus, conus pulmonum menonjol sehingga disimpulkan dari foto thorax tampak kesan kardiomegali dengan konfigurasi *left ventricular hipertrophy* dan *left atrial enlargement* (gambar [-@fig-thorax]).\n\n![Foto Polos Thorax Anteroposterior (6/11/2023) menunjukan kardiomegali dengan konfigurasi LVH dan LAE serta tak tampak kelainan pada pulmo.](image/thorax_ap.jpg){#fig-thorax}\n\n![Elektrokardiografi pasien saat masuk rumah sakit (6/11/2023) menunjukan irama atrial fibrilasi.](image/ecg/heldi_ekg_awal_transform.jpg){#fig-ecgawal}\n\n| Parameter           | Nilai Referensi        | 6/11/2023 | 7/11/2023 | 10/11/2023 |\n|---------------|---------------|---------------|---------------|---------------|\n| WBC                 | 4.1 - 11.0 x 10^3^/µL  | 3.96      | 11.17     | 4.42       |\n| Neutrofil (absolut) | 2.50 - 7.50 x 10^3^/µL | 2.77      | 9.29      | 3.41       |\n| Limfosit (absolut)  | 1.00 - 4.00 x 10^3^/µL | 1.06      | 1.11      | 0.76       |\n| Monosit (absolut)   | 1.00 - 4.00 x 10^3^/µL | 0.13      | 0.77      | 0.25       |\n| Eosinofil (absolut) | 0.00 - 0.50 x 10^3^/µL | 0.00      | 0.00      | 0.00       |\n| Basofil (absolut)   | 0.0 - 0.1 x 10^3^/µL   | 0.00      | 0.00      | 0.00       |\n| Hemoglobin          | 12.0 - 16.0 g/dL       | 7.30      | 6.90      | 11.20      |\n| Hematokrit          | 36.0 - 46.0            | 23.10     | 21.50     | 33.10      |\n| MCV                 | 80.0 - 100.0 fL        | 85.90     | 85.30     | 82.80      |\n| MCH                 | 26.0 - 34.0 pg         | 27.10     | 27.40     | 28         |\n| MCHC                | 31 - 36 g/dL           | 31.60     | 32.10     | 33.80      |\n| Platetet            | 140 - 440 x 10^3^/µL   | 67.00     | 78.00     | 57         |\n\n: Data pemeriksaan darah lengkap selama perawatan pasien. {#tbl-dl}\n\n| Pemeriksaan        | Parameter              | Referensi     | 6/11/2023 | 7/11                         | 12/11 | 14/11     | 16/11 |\n|---------|---------|---------|---------|---------|---------|---------|---------|\n| Marker Inflamasi   | LED                    | \\< 20         | 69        |                              |       |           |       |\n| Faal Hemostasis    | PPT                    | 10 - 12.7     | 15.9      |                              |       |           |       |\n|                    | INR                    | 0.9 - 1.1     | 1.45      |                              |       |           |       |\n|                    | APTT                   | 23-34.7       | 28.9      |                              |       |           |       |\n| Fungsi Ginjal      | BUN                    | 7.0 - 18.7    | 7.0       |                              |       |           |       |\n|                    | Kreatinin              | 0.57 - 1.11   | 0.51      |                              |       |           |       |\n|                    | e-LFG                  | \\>= 90        | 135.53    |                              |       |           |       |\n| Elektrolit         | Natrium                | 136 - 145     | 142       |                              |       |           |       |\n|                    | Kalium                 | 3.5 - 5.1     | 2.88      |                              |       |           |       |\n|                    | Kalsium                | 8.8 - 10.2    |           |                              |       | 7.7 (9.1) |       |\n| Fungsi Liver       | AST/SGOT               | 71            | \\<34      |                              |       | 123       |       |\n|                    | ALT/SGPT               | 44            | \\<55      |                              |       | 118       |       |\n|                    | Albumin                | 3.4 - 4.8     | 2.3       |                              |       |           |       |\n|                    | Globulin               | 2.2 - 3.7     | 4.10      |                              |       |           |       |\n|                    | Total Protein          | 6.4 - 8.3     | 6.4       |                              |       |           |       |\n|                    | Bilirubin Total        | 0.2 - 1.2     | 0.2 - 1.2 | 4.9                          | 5.60  | 4.20      |       |\n|                    | Bilirubin Direk        | 0.0 - 0.5     | 0.0 - 0.5 | 3.2                          | 3.37  | 2.13      |       |\n|                    | Bilirubin Indirek      | 0.2 - 0.7     | 0.2 - 0.7 | 1.70                         | 2.23  | 2.07      |       |\n|                    | Fosfatase Alkali (ALP) | 40 - 150      |           | 125                          |       |           |       |\n|                    | Gamma GT               | \\< 33         |           | 232                          |       |           |       |\n| Hepatitis Marker   | HBsAg                  | Non reaktif   |           | Non reaktif                  |       |           |       |\n|                    | Anti HCV               | Non reaktif   |           | Non reaktif                  |       |           |       |\n| Analisis Gas Darah | pH                     | 7.35 - 7.45   | 7.47      |                              |       |           |       |\n|                    | pCO2                   | 35 - 45       | 44        |                              |       |           |       |\n|                    | HCO3-                  | 22 - 26       | 32        |                              |       |           |       |\n|                    | BEecf                  | -2 s.d 2      | 83        |                              |       |           |       |\n|                    | pO2                    | 80 - 100%     | 75        |                              |       |           |       |\n|                    | SO2c                   | 95 - 100%     | 96        |                              |       |           |       |\n|                    | TCO2                   | 24 - 30       | 33.40     |                              |       |           |       |\n| Coombs Test        | Direct Coombs Test     | Negatif       |           | Positif                      |       |           |       |\n|                    | Indirect Coombs Test   | Negative      |           | Positif                      |       |           |       |\n| Imunologi          | ANA-IF                 | \\< 1:100      |           | 1:10.00 (Pola fine Speckled) |       |           |       |\n|                    | TrAB (PRODIA)          | \\<= 1.75 IU/L |           |                              |       |           | 36.3  |\n| Fungsi Tiroid      | Free T4                | 0.7 - 1.48    |           | 28                           |       |           |       |\n|                    | TSHs                   | 0.27 - 4.20   |           | \\< 0.01                      |       |           |       |\n\n: Data pemeriksaan kimia klinik selama perawatan pasien. {#tbl-kimia}\n\nPemeriksaan elektrokardiografi (EKG) 12 lead saat di IGD menunjukan irama gelombang QRS iregular 140 kali per menit dengan gelombang P yang tidak jelas dan tidak teratur serta tidak sinkron dengan kompleks QRS yang tampak *iregularly iregular* (gambar [-@fig-ecgawal]). Irama EKG mengesankan sebuah irama fibrilasi atrium dengan respon kontraksi ventrikel cepat (AF RVR). Pemeriksaan ekokardiografi *full study* 1 hari perawatan (7/11/2023) menunjukan pembesaran atrium derajat berat dengan ukuran ventrikel kiri, ventrikel kanan, serta atrium kanan dalam batas normal. Fungsi sistolik normal dengan ejeksi fraksi 62.6%, namun fungsi diastolik ventrikel kiri belum dapat ditentukan. Terdapat regurgitasi katup mitral dengan derajat sedang-berat dicurigai akibat prolapse daun katup mitral anterior (*anterior mitral leaflet*). Katup Aorta dan Trikuspid ditemukan mengalami regurgitasi ringan. Tidak ditemukan efusi perikardium. Estimasi tekanan atrium kanan (eRAP) dalam nilai normal (8 mmHg) gambar [-@fig-echo].\n\n::: {#fig-echo layout-nrow=\"2\"}\n![Ekokardiografi tampak ventrikel kiri](/image/echo/echo_chamber.png){#fig-4chamber}\n\n![Ekokardiografi fungsi jantung kanan](/image/echo/echo_rightfunction.png){#fig-rv}\n\n![Ekokardiografi tampak continous wave doppler pada regurgitasi katup mitral](/image/echo/echo_MR.png){#fig-CW}\n\n![Ekokardiografi tampak pulse wave doppler pada regurgitasi katup mitra](/image/echo/echo_MR_2.png){#fig-PWD}\n\nEkokardiografi tampak pembesaran atrium kiri disertai regurgitasi katup mitral derajat sedang-berat.\n:::\n\nPemeriksaan apusan darah tepi menungjukan anemia normokromik, normositer dengan leukositosis dan thrombositopenia. Sebagian besar populasi sel normokromik normositer, anisopoikilositosis (ovalosit, sel tear drop, stomatosit, sel target, sel polikromasia, normoblast). Pada leukosit differential count ditemukan neutrofilia dan tidak ada sel muda. Pada thrombosit tidak ditemukan giant trombosit atau clumping.\n\n| Pemeriksaan Urin             | Parameter                | Referensi       | 7/11/2023 |\n|---------------------|------------------|-----------------|-----------------|\n| Urine Lengkap                | Berat Jenis              | 1.003 - 1.035   | 1.009     |\n|                              | Warna                    | Kuning          | Kuning    |\n|                              | Kekeruhan                |                 | Jernih    |\n|                              | pH                       | 4.5 - 8         | 7.5       |\n|                              | Leukosit                 | Negatif         | Negatif   |\n|                              | Nitrit                   | Negatif         | Negatif   |\n|                              | Protein                  | Negatif         | Negatif   |\n|                              | Glukosa                  | Negatif         | Negatif   |\n|                              | Keton                    | Negatif         | Negatif   |\n|                              | Darah                    | Negatif         | Negatif   |\n|                              | Urobilinogen             | Normal          | Normal    |\n|                              | Bilirubin                | Negatif         | Negatif   |\n|                              | Leukosit Sedimen         | 7 /LPB          | 5         |\n|                              | Eritrosit Sedimen        | 5 /LPB          | 4         |\n|                              | Sel Epitel Sedimen       | 8 /LPB          | 1         |\n|                              | Silinder                 | 2.4 /mikroliter | 0.14      |\n|                              | Bakteri                  | 130.7           | 1993.8    |\n| Rasio Protein kreatinin urin | Mikro Total protein urin | 1 - 14 mg/dl    | 24.10     |\n|                              | Kreatinin urin           | 63 - 166        | 2.41      |\n|                              | Rasio protein kreatinin  | 2.41            | \\< 0.2    |\n| Tes Kehamilan (RS Perujuk)   |                          | Negatif         | Negatif   |\n\n: Data pemeriksaan urin selama perawatan pasien. {#tbl-urin}\n\n| Tangal pemeriksaan | Kalium | Koreksi Kalium                                            |\n|----------------|----------------|----------------------------------------|\n| 6/11/2023          | 2.88   | Drip KCL 50 Meq                                           |\n| 8/11/2023          | 2.95   | Drip KCL 25 Meq                                           |\n| 8/11/2023          | 2.45   | Drip KCL 50 Meq                                           |\n| 9/11/2023          | 3.91   |                                                           |\n| 15/11/2023         | 2.25   | Drip KCL 50 Meq                                           |\n| 16/11/2023         | 3.18   | KSR 500 mg tiap 12 jam per oral (Selanjutnya Rawat Jalan) |\n\n: Data pemantauan kalium selama perawatan pasien. {#tbl-kalium}\n\nDiagnosis kerja pasien meliputi, SLE derajat aktivitas berat dengan anemia sedang normokromik normositer et causa anemia hemolitik, suspek kardiomiopati lupus, atrial fibrilasi *rapid ventricular response*, diare akut et causa suspek infeksi virus dengan dehidrasi ringan-sedang, hipokalemia et causa suspek *loss*. Pada pasien diberikan terapi pulsedose metilprednisolon 500 mg dalam NaCl 0.9% 100 cc intravena habis dalam 30 menit selama 3 hari. Terapi supportif lain meliputi omeprazole 40 mg sebelum pemberian pulse dose metilprednisolon, kandesartan 8 mg tiap 24 jam per oral, oralit ad libitum, drip KCL 50 meq dalam NaCl 0.9% 500 cc habis dalam 8 jam dan transfusi *packed red cell* dengan target hemoglobin \\> 10 g/dL. Pasien dikonsulkan ke divisi kardiologi terkait atrial fibrilasi dan diberikan terapi digoxin 0.5 mg bolus pelan jika denyut jantung \\> 110.\n\nTerkait dengan atrial fibrilasi, pada pasien dilakukan pemeriksaan FT4 dan TSH untuk evaluasi penyebab atrial fibrilasi. Evaluasi paska pemeriksaan FT4 dan TSH yang menunjukan kondisi hipertiroid dicurigai akibat penyakit Graves (skor Wayne 20, tabel [-@tbl-wayne]) disertai gejala klinis sesuai dengan kondisi badai tiroid (thyroid storm) dengan skor Burch Wartofsky 50 poin (tabel [-@tbl-bw]). Terapi diberikan meliputi propanolol 60 mg tiap 6 jam per oral, propiltiourasil (PTU) 600 mg sebagai dosis awal (*loading dose)* dilanjutkan 300 mg tiap 6 jam per oral, steroid dengan metilprednisolon sesuai dosis untuk SLE, serta direncanakan pemberian larutan iodin 5 tetes setiap 8 jam per oral setelah pemberian PTU namun obat tidak tersedia.\n\nTerapi atrial fibrilasi dari kardiologi meliputi digoksin 0.5 mg intravena jika laju denyut jantung \\> 110 kali per menit. Pada pasien didapatkan kondisi hipertensi dengan terapi ramipril 5 mg tiap 12 jam per oral serta nifedipin (lepas lambat) 30 mg tiap 24 jam per oral.\n\n| Gejala onset baru atau memberat | Skor | Nilai | Tanda              | Skor jika ada | Skor jika tidak ada | Nilai |\n|-----------|-----------|-----------|-----------|-----------|-----------|-----------|\n| Dyspnea on effect               | +1   | 0     | Palpable thyroid   | +3            | -3                  | +3    |\n| Palpitations                    | +2   | +2    | Bruit over thyroid | +2            | -2                  | -2    |\n| Tiredness                       | +2   | +2    | Exopthalmoses      | +2            | 0                   | 0     |\n| Preference for heat             | -5   | 0     | Lid retraction     | +2            | 0                   | 0     |\n| Preference for cold             | +5   | +5    | Lid lag            | +1            | 0                   | 0     |\n| Excessive sweating              | +3   | 0     | Hyperkinesis       | +4            | -2                  | -2    |\n| Nervousness                     | +2   | +2    | Hands hot          | +2            | -2                  | -2    |\n| Appetite: increased             | +3   | +3    | Hands moist        | +1            | -1                  | -1    |\n| Appetite: decreased             | -3   | 0     | Casual pulse rate  |               |                     |       |\n| Weight: increased               | -3   | 0     | \\>80/min           | 0             | -3                  | 0     |\n| Weight: decreased               | +3   | +3    | \\>90/min           | +3            | 0                   | +3    |\n|                                 |      |       | Atrial fibrilasi   | +4            | 0                   | +4    |\n\n: Penilaian gejala dan tanda klinis hipertiroid dengan skor Wayne {#tbl-wayne}\n\n| Burch Wartofsky Score            | 7/11/2023 - 9/11/2023                       | 10/11/24 - 12/11/24                          | 13/11/24 - 14/11/24                        | 15/11/24                                     | 16/11/24                                     | 17/11/24                                   |\n|-----------|-----------|-----------|-----------|-----------|-----------|-----------|\n| Temperatur                       | \\< 37.2 (0)                                 | \\< 37.2 (0)                                  | \\< 37.2 (0)                                | \\< 37.2 (0)                                  | \\< 37.2 (0)                                  | \\< 37.2 (0)                                |\n| Disfungsi Sistem Saraf Pusat     | tidak ada (0)                               | tidak ada (0)                                | tidak ada (0)                              | tidak ada (0)                                | tidak ada (0)                                | tidak ada (0)                              |\n| Disfungsi Gastrointestinal-hepar | Berat-jaundice tidak dapat dijelaskan (+20) | Berat-jaundice tidak dapat dijelaskan (+20)  | Keluhan membaik (0)                        | Keluhan membaik (0)                          | Keluhan membaik (0)                          | Keluhan membaik (0)                        |\n| Denyut jantung                   | 110 - 199 (+10)                             | 90 - 109 (+5)                                | 90 - 109 (+5)                              | \\>= 140(+25)                                 | \\>=120 -129 (+15)                            | \\>=90 -109 (+5)                            |\n| Kondisi Gagal jantung Kongestif  | tidak ada (0)                               | tidak ada (0)                                | tidak ada (0)                              | tidak ada (0)                                | tidak ada (0)                                | tidak ada (0)                              |\n| Atrial Fibrilasi                 | Ada (+10)                                   | tidak (0)                                    | ada (10)                                   | ada (10)                                     | ada (10)                                     | ada (10)                                   |\n| Faktor Presipitasi               | Ada (+10)                                   | Ada (+10)                                    | tidak (0)                                  | tidak (0)                                    | tidak (0)                                    | tidak (0)                                  |\n| Total                            | 50 (*Highly suggestive of thyroid storm*)   | 35 (*Suggestive of impending thyroid storm*) | 15 (*Unlikely to represent thyroid storm*) | 35 (*Suggestive of impending thyroid storm*) | 25 (*Suggestive of impending thyroid storm*) | 15 (*Unlikely to represent thyroid storm*) |\n\n: Penilaian derajat gejala hipertiroid dengan skor Burch-Wartofsky {#tbl-bw}\n\nPada pemeriksaan ultrasonografi Tiroid ditemukan peningkatan vaskularisasi pada parenkim tiroid kanan, kiri dan istmus. Pada pemeriksaan tidak ditemukan massa/nodul/kista pada kelenjar tiroid, namun tampak pembesaran kelenjar getah bening pada regio colli kiri, submandibula kanan-kiri, preaurikula kanan dan parotid kiri. Kelenjar parotis kanan tak tampak kelainan. Pemeriksaan USG ini mendukung *Graves Disease* dengan multipel *non suspicious* limfadenopati pada regio colli kiri, submandibula kanan-kiri, preauricula kanan, dan parotid kiri (gambar [-@fig-usgtiroid]). Temuan USG tiroid ini mendukung temuan klinis serta laboratorium untuk penyakit Graves. Penegakan diagnosis pada tahap akhir membutuhkan pemeriksaan Tiroid Receptor Antibody (TRAb) namun kendala teknis laboratorium rumah sakit yang belum mampu melakukan pemeriksaan tersebut. Pemeriksaan TRAb dilakukan pada akhir perawatan pada laboratorium terstandar dengan hasil nilai serum yang diatas batas normal (36.3 IU/L).\n\n::: {#fig-usgtiroid layout-nrow=\"3\"}\n![USG Tiroid Lobus Kanan](/image/usg_tiroid/tiroid_RLobe.png){#fig-Rtiroid}\n\n![USG Tiroid Istmus](/image/usg_tiroid/tiroid_istmus.png){#fig-Istmus}\n\n![USG Tiroid Lobus Kiri](/image/usg_tiroid/tiroid_LLobe.png){#fig-Ltiroid}\n\nUltrasonografi kelenjar tiroid tampak pembesaran ukuran kelenjar, hipoekoik diffuse disertai tampak peningkatakan vaskularisasi pada pencitraan dopler.\n:::\n\nPada pemeriksaan ultrasonografi abdomen ditemukan nodul tunggal hipoechoic dengan hiperechoic di tepinya dan internal echo didalamnya, berbatas tegas tepi regular pada segmen VIII hepar, terukur +/- 1.8 x 1.7 cm yang pada CDUS tampak vaskularisasi pada tepinya. Pada pencitraan cavum pelvis, ditemukan cairan bebas minimal. Tindakan diagnostik lanjutan terkait temuan nodul hepar terbatas pada pemeriksaan USG abdomen. Terapi terkait transaminitis disertai peningkatan bilirubin diberikan berupa terapi supportif berupa curcuma tablet tiap 8 jam per oral serta asam ursodioksikolat 250 mg tiap 8 jam per oral. Pada akhir masa perawatan rumah sakit pemeriksaan bilirubin diulang dan hasilnya menunjukan penurunan kadar bilirubin (tabel [-@tbl-kimia]).\n\n![USG abdomen (9/11/2023) ditemukan liver tidak membesar, permukaan licin, sudut tajam, tepi rata, sistem vasculer dan bilier tampak normal, echoparenchym normal, tampak single nodul hipoechoic dengan hiperechoic di tepinya dan internal echo didalamnya, berbatas tegas tepi regular pada segmen VIII hepar, terukur +/- 1.8 x 1.7 cm yang pada CDUS tampak vaskularisasi pada tepinya.](image/usg_abd/abd_nodul.png){fig-align=\"left\"}\n\nSelama perawatan dialakukan perubahan dosis serta regimen obat antitiroid serta regimen imunosupresan setelah terjadi perbaikan kondisi umum  pasien. Secara ringkas perubahan dosis terapi dirangkum pada gambar [-@fig-obat-tiroid] untuk obat antitiroid dan gambar [-@fig-obat-sle] untuk obat imunosupresan SLE. Obat antiroid awal saat terjadi krisis/badai tiroid adalah PTU dengan diawali dosis *loading* yang kemudian dilakukan penurunan dosis bertahap (*tappering off*) sesuai keadaan klinis. Pada hari perawatan kedelapan(pemberian obat PTU hari keenam) pasien diberikan obat tiamazole sebagai terapi antitiroid rumatan. Terapi penyekat reseptor beta dengan propanolol juga diawali dengan dosis loading yang kemudian dosisnya diturunkan bertahap sesuai klinis. Steroid berupa metilprednisolon diberikan untuk tujuan menekan aktivitas penyakit SLE diawali dengan pemberian *pulse dose* selama 3 hari kemudian dilanjutkandengan dosis bolus yang secara bertahap juga diturunkan sesuai klinis pasien. \n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ndata <- read_sheet(\"https://docs.google.com/spreadsheets/d/18lY7qc-y4WH2ok0-CfF0v8gU6DSN3Y7F3JWTQqJvPoA/edit?gid=0#gid=0\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nℹ Suitable tokens found in the cache, associated with these emails:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n• 'ka.wiryadana@gmail.com'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n• 'wiryadana.linux@gmail.com'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n  Defaulting to the first email.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n! Using an auto-discovered, cached token.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n  To suppress this message, modify your code or options to clearly consent to\n  the use of a cached token.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n  See gargle's \"Non-interactive auth\" vignette for more details:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n  <https://gargle.r-lib.org/articles/non-interactive-auth.html>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nℹ The googlesheets4 package is using a cached token for\n  'ka.wiryadana@gmail.com'.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n✔ Reading from \"data_obat\".\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n✔ Range 'Sheet1'.\n```\n\n\n:::\n:::\n\n::: {#cell-fig-obat-tiroid .cell}\n\n```{.r .cell-code .hidden}\ndata_Graves <- data %>%\n  select(\"day\", \"bw\", \"Propanolol\", \"PTU\", \"Tiamazole\")\n\ndata_long <- data %>%\n  pivot_longer(cols = 2:17, names_to = \"Parameter\", values_to = \"Dosis\")\n\n# endokrin <- ggplot(data_long, aes(x=day, y=Dosis)) +\n#   geom_line( color=\"steelblue\") + \n#   geom_point() +\n#   xlab(\"\") +\n#   theme_ipsum() +\n#   facet_wrap(vars(Parameter), ncol = 1, scales = \"free\", shrink = TRUE) +\n#   labs(x = \"hari\", y = \"\") +\n#   theme(axis.text.y=element_blank())\n\nplot_bw <- ggplot(data, aes(x=day, y=bw)) +\n  geom_line(color = \"grey\") +\n  geom_point(shape=21, color = \"black\", fill=\"#69b3a2\", size=2) +\n  ylab(\"Skor Burch Wartofsky\") +\n  theme_ipsum(axis_title_just = \"cc\") +\n  theme(#axis.text.y = element_blank(),\n        axis.ticks.y = element_blank(),\n        #axis.title.y = element_blank(),\n        axis.title.x = element_blank(),\n        plot.margin = margin(t = 1, b=1) ) +\n  ylim(0,60)\n\n\nplot_propanolol <- ggplot(data, aes(x=day, y=Propanolol)) +\n  geom_line(color = \"grey\") +\n  geom_point(shape=21, color = \"black\", fill=\"#69b3a2\", size=2) +\n  #xlab(\"\") +\n  theme_ipsum(axis_title_just = \"cc\") +\n   theme(axis.text.y = element_blank(),\n        axis.ticks.y = element_blank(),\n        #axis.title.y = element_blank(),\n        axis.title.x = element_blank(),\n        plot.margin = margin(t = 1, b=1) ) +\n  ylim(0,300) +\n  geom_text(data = data[3,], label=\"4 x 60 mg\", vjust=0.1, hjust=1.1) +\n   geom_text(data = data[5,], label=\"3 x 40 mg\", vjust=0, hjust=(-0.2)) +\n  geom_text(data = data[6,], label=\"3 x 10 mg\", vjust=0.2, hjust=1.5) +\n    geom_text(data = data[10,], label=\"3 x 20 mg\", vjust=(-1), hjust=0)\n\n\nplot_ptu <- ggplot(data, aes(x=day, y=PTU)) +\n  geom_line(color = \"grey\") +\n  geom_point(shape=21, color = \"black\", fill=\"#69b3a2\", size=2) +\n  #xlab(\"\") +\n  theme_ipsum(axis_title_just = \"cc\") +\n   theme(axis.text.y = element_blank(),\n        axis.ticks.y = element_blank(),\n        #axis.title.y = element_blank(),\n        axis.title.x = element_blank(),\n        plot.margin = margin(t = 1, b=1) ) +\n  ylim(0,2000)+\n  geom_text(data = data[3,], label=\"Loading 600 mg => 4 x 300 mg \", hjust=(-0.1)) +\n   geom_text(data = data[4,], label=\"4 x 300 mg\", vjust=2, hjust=1) +\n  geom_text(data = data[5,], label=\"3 x 300 mg\", vjust=0, hjust=(-0.1)) +\n    geom_text(data = data[6,], label=\"3 x 100 mg\", vjust=(-1), hjust=0)\n\nplot_tiamazole<- ggplot(data, aes(x=day, y=Tiamazole)) +\n  geom_line(color = \"grey\") +\n  geom_point(shape=21, color = \"black\", fill=\"#69b3a2\", size=2) +\n  xlab(\"Hari Perawatan\") +\n  theme_ipsum(axis_title_just = \"cc\") +\n   theme(axis.text.y = element_blank(),\n        axis.ticks.y = element_blank(),\n        #axis.title.y = element_blank(),\n        plot.margin = margin(t = 1, b=1) )+\n  ylim(0,60)+\n  geom_text(data = data[9,], label=\"mulai Tiamazole 3 x 10 mg\", hjust=(1.2))\n\nplot_Graves <- plot_bw / plot_propanolol / plot_ptu / plot_tiamazole + \n  plot_layout(axes = \"collect\") +\n  plot_annotation(tag_levels = 'A') & \n  theme(plot.tag = element_text(size = 8))\n  \nplot_Graves\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 2 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 2 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 6 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 6 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 8 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 8 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Perubahan dosis obat menyesuaikan klinis hipertiroid](index_files/figure-docx/fig-obat-tiroid-1.png){#fig-obat-tiroid}\n:::\n:::\n\n::: {#cell-fig-obat-sle .cell}\n\n```{.r .cell-code .hidden}\nplot_metilprednisolon <- ggplot(data, aes(x=day, y=metilprednisolon)) +\n  geom_line(color = \"grey\") +\n  geom_point(shape=21, color = \"black\", fill=\"#69b3a2\", size=2) +\n  ylab(\"Metilprednisolon\") +\n  theme_ipsum(axis_title_just = \"cc\") +\n   theme(axis.text.y = element_blank(),\n        axis.ticks.y = element_blank(),\n        #axis.title.y = element_blank(),\n        axis.title.x = element_blank(),\n        plot.margin = margin(t = 1, b=1) ) +\n  ylim(0,600) +\n  geom_text(data = data[3,], label=\"Metilprednisolon Pulse Dose 1 x 500 mg\", hjust=(-0.1)) +\n   geom_text(data = data[4,], label=\"1 x 125 mg\", vjust=0, hjust=1.1) +\n  geom_text(data = data[6,], label=\"1 x 62,5 mg\", vjust= (-1), hjust=0) +\n    geom_text(data = data[8,], label=\"2 x 16 mg\", vjust=(-1), hjust=(-1))\n\nplot_hcq <- ggplot(data, aes(x=day, y=hidroksiklorokuin)) +\n  geom_line(color = \"grey\") +\n  geom_point(shape=21, color = \"black\", fill=\"#69b3a2\", size=2) +\n  ylab(\"Hidroklorokuin\") +\n  theme_ipsum(axis_title_just = \"cc\") +\n   theme(axis.text.y = element_blank(),\n        axis.ticks.y = element_blank(),\n        #axis.title.y = element_blank(),\n        axis.title.x = element_blank(),\n        plot.margin = margin(t = 1, b=1) ) +\n  geom_text(data = data[9,], label=\"mulai hidroksikloroquin 1 x 200 mg\", hjust=(1.2))\n\nplot_kamifet<- ggplot(data, aes(x=day, y=kamifet)) +\n  geom_line(color = \"grey\") +\n  geom_point(shape=21, color = \"black\", fill=\"#69b3a2\", size=2) +\n  ylab(\"Micofenolat Mofetil\") +\n  xlab(\"Hari Perawatan\") +\n  theme_ipsum(axis_title_just = \"cc\") +\n   theme(axis.text.y = element_blank(),\n        axis.ticks.y = element_blank(),\n        #axis.title.y = element_blank(),\n        plot.margin = margin(t = 1, b=1) ) +\n  geom_text(data = data[9,], label=\"mulai MMF 2 x 1000 mg\", hjust=(1.2))\n\nplot_sle <- plot_metilprednisolon / plot_hcq / plot_kamifet + \n  plot_layout(axes = \"collect\") +\n  plot_annotation(tag_levels = 'A') & \n  theme(plot.tag = element_text(size = 8))\n  \nplot_sle\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 8 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 8 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 8 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 8 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Perubahan dosis obat imunosupresan untuk penyakit SLE](index_files/figure-docx/fig-obat-sle-1.png){#fig-obat-sle}\n:::\n:::\n\n\n\n## Diskusi\n\nPenelitian terbaru oleh Xian et al menemukan bahwa SLE meningkatkan risiko penyaki Graves (OR=1.13, 95% CI 1.05-1.22, p =0.003), dan berlaku juga sebaliknya penyakit Graves meningkatkan risiko SLE (OR=1.27, 95% CI 1.09-1.48, p =0.018).[@xian2024] Hubungan sebab akibat antara penyakit Graves dan SLE yang ditemukan dalam penelitian tersebut semakin menegaskan temuan epidemiologi sebelumnya. Patogenesis SLE dan penyakit Graves mungkin dipengaruhi oleh mutasi pada gen HLA. Sebuah meta-analisis yang dilakukan sebelumnya menemukan bahwa mutasi pada HLA-DR3 dan HLA-DR15 secara signifikan meningkatkan kemungkinan SLE.[@xue_2018] Kehadiran gen HLA yang bermutasi dapat mengakibatkan perubahan kompleks HLA pada sel penyaji antigen (*antigen presenting cell*), sehingga mempengaruhi interaksi antara sel-B dan sel-T. Kondisi ini dapat menyebabkan disregulasi sel B yang reaktif terhadap protein sendiri (*self protein*) dan diikuti dengan produksi autoantibodi yang dapat berfungsi sebagai mediator efek kausal SLE pada penyakit Graves.[@xian2024]\n\nSelain gen terkait HLA, gen non-HLA juga diduga memainkan peran penting dalam interaksi antara SLE dan penyakit Graves. Protein terkait selm limfosit T sitotoksik 4 (CTLA-4) adalah reseptor protein yang berfungsi sebagai cek poin pemeriksaan imun untuk menurunkan regulasi respons imun dengan mengikat ligan CD80 dan CD86 pada permukaan antigen presenting cell, sehingga dapat terjadi regulasi aktivasi sel-T dan proliferasinya.[@syn2017] Mutasi pada gen CTLA-4 telah dikaitkan dengan SLE dan penyakit Graves. Sebuah meta-analisis menunjukkan bahwa polimorfisme gen CTLA-4 pada populasi Asia dikaitkan dengan risiko SLE.[@zhai2013] Sebuah studi oleh Lee dkk. menemukan bahwa beberapa polimorfisme nukleotida tunggal CTLA-4 dikaitkan dengan penyakit Graves dan penyakit tiroid autoimun seperti tiroiditis Hashimoto.[@lee2015] Mutasi pada gen CTLA-4 dapat menyebabkan defisiensi regulasi penurunan regulasi respon imun sel-T, yang mengakibatkan hiperaktivasi sel-T dan dengan demikian memicu penyakit autoimun. Faktor ini mungkin juga memainkan peran mediasi dalam hubungan antara penyakit Graves dan SLE.[@xian2024]\n\nSLE dan penyakit Graves ditandai oleh kelainan regulasi imun yang mungkin berhubungan erat dengan interferon tipe I (IFN-I).[@pan2019] Interferon tipe I, termasuk IFN-a, IFN-b, IFN-ϵ, IFN-k, dan lain-lainya adalah sitokin yang memainkan peran penting dalam peradangan, regulasi imunitas, pengenalan sel tumor, dan respons sel T. Dalam konteks penyakit autoimun, IFN-I dapat berkontribusi pada perkembangan SLE dengan meningkatkan presentasi antigen dan respon limfosit serta menginduksi ekspresi kemokin. IFN-I meningkatkan aktivasi sel B, diferensiasi, proliferasi dan produksi antibodi, dan dapat menginduksi ekspresi reseptor *Thyroid-timulating hormone*.[@ivashkiv2013] Dengan demikian, hal ini mungkin berdampak pada menignkatnya risiko penyakit Graves.\n\nJalur imunologi yang sama dalam perkembangan SLE dan penyakit Graves ditunjukkan oleh adanya tumpang tindih kemokin dan sitokin spesifik. Penelitian terbaru berfokus pada interaksi antara CXCL10 dan CXCR3 dalam respon imun T helper 1 sangat penting dalam etiologi penyakit Graves dan SLE.[@antonelli2014; @antonelli2020] Selain itu, dilaporkan bahwa peningkatan kadar IL-37 berkorelasi positif dengan konsentrasi TRAb dan derajat aktivitas SLE, sehingga ini menunjukkan bahwa IL-37 memainkan peran penting dalam terjadinya penyakit Graves dan SLE.[@xu2015]\n\nSelain regulasi imun yang menyimpang, SLE dan penyakit Graves mungkin memiliki patogenesis yang sama terkait autoantibodi yang menyebabkan kerusakan jaringan. Sebuah meta-analisis yang dilakukan oleh Pan et al. menunjukkan bahwa kadar antibodi tiroid peroksidase (TPOAb) dan antibodi tiroglobulin (TgAb) jauh lebih tinggi pada pasien SLE dibandingkan dengan populasi sehat, yang menunjukkan adanya korelasi antara SLE dan penyakit tiroid autoimun.[@pan2015] Penelitian yang dilakukan oleh Lanzolla dkk. menunjukkan bahwa keberadaan antibodi antinuklear diamati pada sekitar 80% pasien yang didiagnosis dengan penyakit Graves. Temuan ini menunjukkan bahwa penyakit Graves berpotensi mempengaruhi perkembangan SLE melalui jalur autoantibodi.[@lanzolla2022]\n\n\n## Ringkasan\n\nPenyakit Graves secara genetik diprediksi meningkatkan risiko SLE, dan berlaku juga sebaliknya. Laporan kasus ini diharapkan dapat memberikan dasar baru untuk skrining dan tatalaksana pasien dengan penyakit Graves yang memiliki gejala baru yang tidak spesifik harus diskrining untuk SLE sehingga memfasilitasi diagnosis dan pengobatan tepat waktu dan menghindari penundaan atau eksaserbasi penyakit. Pada saat yang sama, fungsi tiroid juga perlu dipantau selama penatalaksanaan pasien SLE, sehingga dapat menyesuaikan rencana pengobatan dan meningkatkan kualitas hidup pasien.\n\n## Daftar Pustaka\n",
    "supporting": [
      "index_files/figure-docx"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}