<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Penyakit Graves pada seorang perempuan dengan Sistemik Lupus Eritematosus</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>


<meta name="citation_title" content="Penyakit Graves pada seorang perempuan dengan Sistemik Lupus Eritematosus">
<meta name="citation_author" content="dr. Kadek Adit Wiryadana">
<meta name="citation_author" content="dr. I Made Siswadi Semadi, M.Biomed, SpPD, K-EMD">
<meta name="citation_author" content="dr. Pande Ketut Kurniari, SpPD, K-R">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=Literate programming;,citation_author=Donald E. Knuth;,citation_publication_date=1984-05;,citation_cover_date=1984-05;,citation_year=1984;,citation_fulltext_html_url=https://doi.org/10.1093/comjnl/27.2.97;,citation_issue=2;,citation_doi=10.1093/comjnl/27.2.97;,citation_issn=0010-4620;,citation_volume=27;,citation_journal_title=Comput. J.;,citation_publisher=Oxford University Press, Inc.;">
<meta name="citation_reference" content="citation_title=Graves’ disease and systemic lupus erythematosus: A mendelian randomization study;,citation_author=Wei Xian;,citation_author=Boyuan Liu;,citation_author=Jinjian Li;,citation_author=Yuxin Yang;,citation_author=Shubin Hong;,citation_author=Haipeng Xiao;,citation_author=Dide Wu;,citation_author=Yanbing Li;,citation_publication_date=2024-01-29;,citation_cover_date=2024-01-29;,citation_year=2024;,citation_fulltext_html_url=http://dx.doi.org/10.3389/fimmu.2024.1273358;,citation_doi=10.3389/fimmu.2024.1273358;,citation_volume=15;,citation_journal_title=Frontiers in Immunology;">
<meta name="citation_reference" content="citation_title=Graves’ Disease;,citation_author=Terry J. Smith;,citation_author=Laszlo Hegedüs;,citation_editor=Dan L. Longo;,citation_publication_date=2016-10-20;,citation_cover_date=2016-10-20;,citation_year=2016;,citation_fulltext_html_url=http://dx.doi.org/10.1056/NEJMra1510030;,citation_issue=16;,citation_doi=10.1056/nejmra1510030;,citation_volume=375;,citation_language=en;,citation_journal_title=New England Journal of Medicine;">
<meta name="citation_reference" content="citation_title=Graves’ disease;,citation_author=Terry F. Davies;,citation_author=Stig Andersen;,citation_author=Rauf Latif;,citation_author=Yuji Nagayama;,citation_author=Giuseppe Barbesino;,citation_author=Maria Brito;,citation_author=Anja K. Eckstein;,citation_author=Alex Stagnaro-Green;,citation_author=George J. Kahaly;,citation_publication_date=2020-07-02;,citation_cover_date=2020-07-02;,citation_year=2020;,citation_fulltext_html_url=http://dx.doi.org/10.1038/s41572-020-0184-y;,citation_issue=1;,citation_doi=10.1038/s41572-020-0184-y;,citation_volume=6;,citation_language=en;,citation_journal_title=Nature Reviews Disease Primers;">
<meta name="citation_reference" content="citation_title=The association of other autoimmune diseases in patients with Graves’ disease (with or without ophthalmopathy): Review of the literature and report of a large series;,citation_author=Silvia Martina Ferrari;,citation_author=Poupak Fallahi;,citation_author=Ilaria Ruffilli;,citation_author=Giusy Elia;,citation_author=Francesca Ragusa;,citation_author=Salvatore Benvenga;,citation_author=Alessandro Antonelli;,citation_publication_date=2019-03;,citation_cover_date=2019-03;,citation_year=2019;,citation_fulltext_html_url=http://dx.doi.org/10.1016/j.autrev.2018.10.001;,citation_issue=3;,citation_doi=10.1016/j.autrev.2018.10.001;,citation_volume=18;,citation_language=en;,citation_journal_title=Autoimmunity Reviews;">
<meta name="citation_reference" content="citation_title=Association between Graves’ disease and risk of incident systemic lupus erythematosus: A nationwide population-based cohort study;,citation_author=Cho Lee;,citation_author=Shih-Fen Chen;,citation_author=Yu-Cih Yang;,citation_author=Chung Y. Hsu;,citation_author=Yu-Chih Shen;,citation_publication_date=2020-11-19;,citation_cover_date=2020-11-19;,citation_year=2020;,citation_fulltext_html_url=http://dx.doi.org/10.1111/1756-185x.14027;,citation_issue=2;,citation_doi=10.1111/1756-185x.14027;,citation_volume=24;,citation_language=en;,citation_journal_title=International Journal of Rheumatic Diseases;">
<meta name="citation_reference" content="citation_title=Association of HLA-DR3 and HLA-DR15 Polymorphisms with Risk of Systemic Lupus Erythematosus.;,citation_abstract=BACKGROUND: Systemic lupus erythematosus (SLE) is an autoimmune disease under genetic control. Growing evidences support the genetic predisposition of HLA-DRB1 gene polymorphisms to SLE, yet the results are not often reproducible. The purpose of this study was to assess the association of two polymorphisms of HLA-DRB1 gene (HLA-DR3 and HLA-DR15) with the risk of SLE via a comprehensive meta-analysis. METHODS: This study complied with the Preferred Reporting Items for Systematic Reviews and Meta-Analyses statement. Case-control studies on HLA-DRB1 and SLE were searched from PubMed, Elsevier Science, Springer Link, Medline, and Cochrane Library database as of June 2018. Analysis was based on the random-effects model using STATA software version 14.0. RESULTS: A total of 23 studies were retained for analysis, including 5261 cases and 9838 controls. Overall analysis revealed that HLA-DR3 and HLA-DR15 polymorphisms were associated with the significant risk of SLE (odds ratio [OR]: 1.60, 95% confidence interval (CI): 1.316-1.934, P = 0.129 and OR: 1.68, 95% CI: 1.334-2.112, P = 0.001, respectively). Subgroup analyses demonstrated that for both HLA-DR3 and HLA-DR15 polymorphisms, ethnicity was a possible source of heterogeneity. Specifically, HLA-DR3 polymorphism was not associated with SLE in White populations (OR: 1.60, 95% CI: 1.320-1.960, P = 0.522) and HLA-DR15 polymorphism in East Asian populations (OR: 1.65, 95% CI: 1.248-2.173, P = 0.001). In addition, source of control was another possible source for both HLA-DR3 and HLA-DR15 polymorphisms, with observable significance for HLA-DR3 in only population-based studies (OR: 1.65, 95% CI: 1.370-1.990, P = 0.244) and for HLA-DR15 in both population-based and hospital-based studies (OR: 1.38, 95% CI: 1.078-1.760, P = 0.123 and OR: 2.08, 95% CI: 1.738-2.490, P = 0.881, respectively). CONCLUSIONS: HLA-DRB1 gene may be a SLE-susceptibility gene, and it shows evident ethnic heterogeneity. Further prospective validations across multiple ethnical groups are warranted.;,citation_author=Ke Xue;,citation_author=Wen-Quan Niu;,citation_author=Yong Cui;,citation_publication_date=2018-12;,citation_cover_date=2018-12;,citation_year=2018;,citation_issue=23;,citation_doi=10.4103/0366-6999.246058;,citation_issn=2542-5641 0366-6999;,citation_pmid=30511687;,citation_volume=131;,citation_journal_title=Chinese medical journal;">
<meta name="citation_reference" content="citation_title=De-novo and acquired resistance to immune checkpoint targeting;,citation_author=Nicholas L Syn;,citation_author=Michele W L Teng;,citation_author=Tony S K Mok;,citation_author=Ross A Soo;,citation_publication_date=2017-12;,citation_cover_date=2017-12;,citation_year=2017;,citation_fulltext_html_url=http://dx.doi.org/10.1016/s1470-2045(17)30607-1;,citation_issue=12;,citation_doi=10.1016/s1470-2045(17)30607-1;,citation_volume=18;,citation_language=en;,citation_journal_title=The Lancet Oncology;">
<meta name="citation_reference" content="citation_title=CTLA-4 polymorphisms and systemic lupus erythematosus (SLE): a meta-analysis;,citation_author=Jin-Xia Zhai;,citation_author=Li-Wei Zou;,citation_author=Zhao-Xiang Zhang;,citation_author=Wen-Jing Fan;,citation_author=Han-Yong Wang;,citation_author=Ting Liu;,citation_author=Zheng Ren;,citation_author=Rui-Xue Dai;,citation_author=Dongqing Ye;,citation_publication_date=2013-08-07;,citation_cover_date=2013-08-07;,citation_year=2013;,citation_fulltext_html_url=http://dx.doi.org/10.1007/s11033-012-2125-7;,citation_issue=9;,citation_doi=10.1007/s11033-012-2125-7;,citation_volume=40;,citation_language=en;,citation_journal_title=Molecular Biology Reports;">
<meta name="citation_reference" content="citation_title=Immunogenetics of autoimmune thyroid diseases: A comprehensive review;,citation_author=Hanna J. Lee;,citation_author=Cheuk Wun Li;,citation_author=Sara Salehi Hammerstad;,citation_author=Mihaela Stefan;,citation_author=Yaron Tomer;,citation_publication_date=2015-11;,citation_cover_date=2015-11;,citation_year=2015;,citation_fulltext_html_url=http://dx.doi.org/10.1016/j.jaut.2015.07.009;,citation_doi=10.1016/j.jaut.2015.07.009;,citation_volume=64;,citation_language=en;,citation_journal_title=Journal of Autoimmunity;">
<meta name="citation_reference" content="citation_title=Immunological pathogenesis and treatment of systemic lupus erythematosus;,citation_author=Lu Pan;,citation_author=Mei-Ping Lu;,citation_author=Jing-Hua Wang;,citation_author=Meng Xu;,citation_author=Si-Rui Yang;,citation_publication_date=2019-02-22;,citation_cover_date=2019-02-22;,citation_year=2019;,citation_fulltext_html_url=http://dx.doi.org/10.1007/s12519-019-00229-3;,citation_issue=1;,citation_doi=10.1007/s12519-019-00229-3;,citation_volume=16;,citation_language=en;,citation_journal_title=World Journal of Pediatrics;">
<meta name="citation_reference" content="citation_title=Regulation of type I interferon responses;,citation_author=Lionel B. Ivashkiv;,citation_author=Laura T. Donlin;,citation_publication_date=2013-12-23;,citation_cover_date=2013-12-23;,citation_year=2013;,citation_fulltext_html_url=http://dx.doi.org/10.1038/nri3581;,citation_issue=1;,citation_doi=10.1038/nri3581;,citation_volume=14;,citation_language=en;,citation_journal_title=Nature Reviews Immunology;">
<meta name="citation_reference" content="citation_title=Patients with Systemic Lupus Erythematosus Have Higher Prevalence of Thyroid Autoantibodies: A Systematic Review and Meta-Analysis;,citation_author=Xi-Feng Pan;,citation_author=Jian-Qiu Gu;,citation_author=Zhong-Yan Shan;,citation_editor=Shervin Assassi;,citation_publication_date=2015-04-23;,citation_cover_date=2015-04-23;,citation_year=2015;,citation_fulltext_html_url=http://dx.doi.org/10.1371/journal.pone.0123291;,citation_issue=4;,citation_doi=10.1371/journal.pone.0123291;,citation_volume=10;,citation_language=en;,citation_journal_title=PLOS ONE;">
<meta name="citation_reference" content="citation_title=Anti-nuclear autoantibodies in Graves’ disease and Graves’ orbitopathy;,citation_author=G. Lanzolla;,citation_author=L. Puccinelli;,citation_author=M. Giudetti;,citation_author=S. Comi;,citation_author=F. Menconi;,citation_author=M. N. Maglionico;,citation_author=C. Posarelli;,citation_author=M. Figus;,citation_author=C. Marcocci;,citation_author=M. Marinò;,citation_publication_date=2022-08-27;,citation_cover_date=2022-08-27;,citation_year=2022;,citation_fulltext_html_url=http://dx.doi.org/10.1007/s40618-022-01906-3;,citation_issue=2;,citation_doi=10.1007/s40618-022-01906-3;,citation_volume=46;,citation_language=en;,citation_journal_title=Journal of Endocrinological Investigation;">
<meta name="citation_reference" content="citation_title=Graves’ disease: Clinical manifestations, immune pathogenesis (cytokines and chemokines) and therapy;,citation_author=Alessandro Antonelli;,citation_author=Poupak Fallahi;,citation_author=Giusy Elia;,citation_author=Francesca Ragusa;,citation_author=Sabrina Rosaria Paparo;,citation_author=Ilaria Ruffilli;,citation_author=Armando Patrizio;,citation_author=Debora Gonnella;,citation_author=Claudia Giusti;,citation_author=Camilla Virili;,citation_author=Marco Centanni;,citation_author=Yehuda Shoenfeld;,citation_author=Silvia Martina Ferrari;,citation_publication_date=2020-01;,citation_cover_date=2020-01;,citation_year=2020;,citation_fulltext_html_url=http://dx.doi.org/10.1016/j.beem.2020.101388;,citation_issue=1;,citation_doi=10.1016/j.beem.2020.101388;,citation_volume=34;,citation_language=en;,citation_journal_title=Best Practice &amp;amp;amp; Research Clinical Endocrinology &amp; Metabolism;">
<meta name="citation_reference" content="citation_title=Chemokine (CXC motif) ligand (CXCL)10 in autoimmune diseases;,citation_author=Alessandro Antonelli;,citation_author=Silvia Martina Ferrari;,citation_author=Dilia Giuggioli;,citation_author=Ele Ferrannini;,citation_author=Clodoveo Ferri;,citation_author=Poupak Fallahi;,citation_publication_date=2014-03;,citation_cover_date=2014-03;,citation_year=2014;,citation_fulltext_html_url=http://dx.doi.org/10.1016/j.autrev.2013.10.010;,citation_issue=3;,citation_doi=10.1016/j.autrev.2013.10.010;,citation_volume=13;,citation_language=en;,citation_journal_title=Autoimmunity Reviews;">
<meta name="citation_reference" content="citation_title=Insights into IL-37, the role in autoimmune diseases;,citation_author=Wang-Dong Xu;,citation_author=Yi Zhao;,citation_author=Yi Liu;,citation_publication_date=2015-12;,citation_cover_date=2015-12;,citation_year=2015;,citation_fulltext_html_url=http://dx.doi.org/10.1016/j.autrev.2015.08.006;,citation_issue=12;,citation_doi=10.1016/j.autrev.2015.08.006;,citation_volume=14;,citation_language=en;,citation_journal_title=Autoimmunity Reviews;">
<meta name="citation_reference" content="">
</head>

<body>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Penyakit Graves pada seorang perempuan dengan Sistemik Lupus Eritematosus</h1>
          </div>

    
    <div class="quarto-title-meta-container">
      <div class="quarto-title-meta-column-start">
            <div class="quarto-title-meta-author">
          <div class="quarto-title-meta-heading">Authors</div>
          <div class="quarto-title-meta-heading">Affiliation</div>
          
                <div class="quarto-title-meta-contents">
            <p class="author">dr. Kadek Adit Wiryadana </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        Universitas Udayana
                      </p>
                  </div>
                      <div class="quarto-title-meta-contents">
            <p class="author">dr. I Made Siswadi Semadi, M.Biomed, SpPD, K-EMD </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        Universitas Udayana
                      </p>
                  </div>
                      <div class="quarto-title-meta-contents">
            <p class="author">dr. Pande Ketut Kurniari, SpPD, K-R </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        Universitas Udayana
                      </p>
                  </div>
                    </div>
        
        <div class="quarto-title-meta">

                      
          
                
              </div>
      </div>
      <div class="quarto-title-meta-column-end quarto-other-formats-target">
      <div class="quarto-alternate-formats"><div class="quarto-title-meta-heading">Other Formats</div><div class="quarto-title-meta-contents"><p><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></p></div><div class="quarto-title-meta-contents"><p><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF (plos)</a></p></div><div class="quarto-title-meta-contents"><p><a href="index-meca.zip" data-meca-link="true"><i class="bi bi-archive"></i>MECA Bundle</a></p></div></div></div>
    </div>



    <div class="quarto-other-links-text-target">
    </div>  </div>
</header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#pendahuluan" id="toc-pendahuluan" class="nav-link" data-scroll-target="#pendahuluan">Pendahuluan</a></li>
  <li><a href="#laporan-kasus" id="toc-laporan-kasus" class="nav-link" data-scroll-target="#laporan-kasus">Laporan Kasus</a></li>
  <li><a href="#diskusi" id="toc-diskusi" class="nav-link" data-scroll-target="#diskusi">Diskusi</a></li>
  <li><a href="#ringkasan" id="toc-ringkasan" class="nav-link" data-scroll-target="#ringkasan">Ringkasan</a></li>
  <li><a href="#daftar-pustaka" id="toc-daftar-pustaka" class="nav-link" data-scroll-target="#daftar-pustaka">Daftar Pustaka</a></li>
  </ul>
<div class="quarto-alternate-notebooks"><h2>Notebooks</h2><ul><li><a href="index-preview.html"><i class="bi bi-journal-code"></i>Article Notebook</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">



  


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p><strong>keywords</strong>:</p>
</section>
<section id="pendahuluan" class="level2">
<h2 class="anchored" data-anchor-id="pendahuluan">Pendahuluan</h2>
<p>Koinsidensi penyakit graves dan sistemik lupus eritematosus (SLE) belakangan ini mendapat perhatian lebih karena ditemukan memiliki hubungan yang tidak sekedar sesuatu yang terjadi secara acak. Hubungan kausal antara kedua entitas penyakit automimun tersebut masih belum banyak diketahui dan saat ini masih terdapat berbagai penelitian yang mendalami hal tersebut.<span class="citation" data-cites="xian2024"><sup><a href="#ref-xian2024" role="doc-biblioref">1</a></sup></span> Penyakit graves merupakan salah satu penyakit autoimun pada organ endokrin tiroid dan merupakan penyebab utama hipertiroidisme.<span class="citation" data-cites="smith2016"><sup><a href="#ref-smith2016" role="doc-biblioref">2</a></sup></span> Insiden enyakit Graves sebagai penyakit autoimun termasuk cukup tinggi dengan rentang 20 - 50 kasus per 100.000 individual serta tingkat prevalensi diperkirakan 1 - 1.5%.<span class="citation" data-cites="davies2020"><sup><a href="#ref-davies2020" role="doc-biblioref">3</a></sup></span> Penyakit graves memilki target organ khusus, namun koinsidensi dengan penyakit autoimun lain seperti SLE, rheumatoid arthritis, multipel sklerosis, diabetes tipe 1 dan lainnya diperkirakan sekitar 16,7% dari total pasien dengan penyakit Graves. Data lebih lanjut dari laporan serial kasus terbaru juga menunjukan bahwa persentase pasien dengan penyakit Graves juga ditemukan memiliki 3 penyakit autoimun lain sebesar 1.5%.<span class="citation" data-cites="ferrari2019"><sup><a href="#ref-ferrari2019" role="doc-biblioref">4</a></sup></span></p>
<p>SLE merupakan penyakit yang memiliki variasi spektrum klinis yang luas akibat terget organ penyakit yang multipel dan heterogen. Penelitian kohort multisenter di China menemukan bahwa individu dengan penyakit Graves lebih rentan mengalami SLE dibanding individu kontrol yang sehat.<span class="citation" data-cites="lee2020"><sup><a href="#ref-lee2020" role="doc-biblioref">5</a></sup></span> Penelitian terbaru dari Xian et al dengan analisis randomisasi mendelian menemukan bahwa terdapat korelasi antara penyakit Graves dengan SLE, dan masing-masing entitas autoimun tersebut saling mendukung untuk koinsidensi autoimun lainnya. Beberapa temuan ini memberikan gambaran bahwa pada praktik klinis diharapkan klinisi dapat meningkatkan skrining penyakit autoimun khususnya penyakit Graves atau SLE saat menegakan diagnosis salah satu penyakit autoimun tersebut.<span class="citation" data-cites="xian2024"><sup><a href="#ref-xian2024" role="doc-biblioref">1</a></sup></span> Laporan kasus ini memaparkan seorang pasien perempuan dengan krisis tiroid akibat penyakit Graves yang terlebih dahulu mengalami atrial fibrilasi dan baru terdiagnosis SLE.</p>
</section>
<section id="laporan-kasus" class="level2">
<h2 class="anchored" data-anchor-id="laporan-kasus">Laporan Kasus</h2>
<p>Seorang perempuan (23066258) usia 23 tahun datang ke instalasi gawat darurat dirujuk dengan keluhan utama dada berdebar sejak 1 hari sebelum masuk rumah sakit perujuk. Selain dada berdebar, pasien mengeluh mual dan pusing sejak 1 bulan sebelumya disertai rambut rontok, ruam kemerahan pada pipi serta nyeri pada persendian kedua kaki yang muncul hilang timbul sejak 1 minggu sebelumnya. Pasien mengalami diare berulang sejak 2 bulan terakhir, serta diare terakhir mulai 4 hari sebelum masuk rumah sakit. Diare konsistensi feses lunak hingga cair, tanpa darah dan tidak disertai nyeri perut. Pasien mengalami penurunan berat badan 10 kg dalam kurun waktu 6 bulan terakhir. Riwayat demam lama dan kencing berbuih disangkal. Menstruasi pasien dikatakan tidak teratur dan menstruasi terakhir 6 bulan sebelum masuk rumah sakit. Pasien belum menikah dan menyangkal adanya riwayat berhubungan seksual.</p>
<p>Riwayat penyakit kronis seperti diabetes, penyakit jantung, penyakit ginjal disangkal. Pasien memiliki riwayat nyeri hilang timbul pada ulu hati sejak kecil yang membaik dengan membeli obat secara mandiri. Riwayat nyeri tenggorokan dikatakan pada 6 bulan sebelumnya namun hanya kurang dari 1 minggu dan telah mendapatkan pengobatan dari dokter THT. Pasien sebelum rawat inap tidak dalam pengobatan rutin, namun pada rumah sakit perujuk pasien telah mendapatkan perawatan selama 4 hari namun tidak membaik dengan diagnosis suspek SLE, anemia sedang, kardiomiopati lupus, atrial flutter dan observasi nodul hepar. Saat dirujuk pasien mendapatkan terapi drip KCL 50 meq, seftriakson 1 gram tiap 12 jam intravena, metilprednisolon 125 mg tiap 12 jam intravena, parasetamol 650 mg tiap 8 jam per oral, Kalium Slow Release 600 mg tiap 8 jam per oral, bisoprolol 2.5 mg tiap 24 jam per oral, ramipril 5 mg tiap 24 jam per oral. Sebelum sakit memberat, pasien menjalani kuliah di malang kemudian 1 minggu sebelum masuk rumah sakit pasien mengunjungi keluarganya di Denpasar.</p>
<p>Saat di IGD pasien dalam kondisi compos mentis, tekanan darah 130/90 mmHg, denyut nadi 128 kali/menit dengan irama iregular dan kuat angkat, laju respirasi 24 kali/menit, saturasi oksigen 99% dengan udara ruangan dan suhu aksila 36.6 C. Pasien tampak sakit berat dan malnutrisi (tinggi badan 155 cm, berat badan terakhir 34 kg, IMT 14.5 kg/m<sup>2</sup>, lingkar lengan atas 18 cm). Temuan signifikan pada pemeriksaan fisik meliputi sklera ikterus, ruam malar, kardiomegali, bilateral pedal edema dan makula hiperemis tersebar pada beberapa bagian tubuh (gambar <a href="#fig-fotoklinis" class="quarto-xref">1</a>). Pada pasien tidak ditemukan adanya organomegali maupun efusi sendi.</p>
<div id="fig-fotoklinis" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fotoklinis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-fotoklinis" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-blkgkiri" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-blkgkiri-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./image/klinis/heldi_leherbelakangkiri.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-1" data-gallery="fig-fotoklinis"><img src="./image/klinis/heldi_leherbelakangkiri.jpg" class="img-fluid figure-img" data-ref-parent="fig-fotoklinis"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-blkgkiri-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Ruam pada belakang telinga kiri
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-fotoklinis" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-wajah" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-wajah-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./image/klinis/heldi_wajahdepan.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-2" data-gallery="fig-fotoklinis"><img src="./image/klinis/heldi_wajahdepan.jpg" class="img-fluid figure-img" data-ref-parent="fig-fotoklinis"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-wajah-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Foto klinis wajah
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-fotoklinis" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-blkgkanan" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-blkgkanan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./image/klinis/heldi_fotoleherbelakangkanan.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-3" data-gallery="fig-fotoklinis"><img src="./image/klinis/heldi_fotoleherbelakangkanan.jpg" class="img-fluid figure-img" data-ref-parent="fig-fotoklinis"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-blkgkanan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Ruam pada belakang telinga kanan
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-fotoklinis" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-leherkanan" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-leherkanan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./image/klinis/haim_leherkanan.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-4" data-gallery="fig-fotoklinis"><img src="./image/klinis/haim_leherkanan.jpg" class="img-fluid figure-img" data-ref-parent="fig-fotoklinis"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-leherkanan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) Foto klinis leher kanan
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-fotoklinis" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-leherdepan" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-leherdepan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./image/klinis/heldi_leherdepan.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-5" data-gallery="fig-fotoklinis"><img src="./image/klinis/heldi_leherdepan.jpg" class="img-fluid figure-img" data-ref-parent="fig-fotoklinis"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-leherdepan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(e) Foto klinis leher depan
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-fotoklinis" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-leherkiri" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-leherkiri-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./image/klinis/heldi_leherkiri.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-6" data-gallery="fig-fotoklinis"><img src="./image/klinis/heldi_leherkiri.jpg" class="img-fluid figure-img" data-ref-parent="fig-fotoklinis"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-leherkiri-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(f) Foto klinis leher kiri
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-fotoklinis" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-tangan" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-tangan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./image/klinis/haim_keduatangan.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-7" data-gallery="fig-fotoklinis"><img src="./image/klinis/haim_keduatangan.jpg" class="img-fluid figure-img" data-ref-parent="fig-fotoklinis"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-tangan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(g) Foto klinis kedua tangan
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-fotoklinis" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-mata" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mata-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./image/klinis/heldi_mata.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-8" data-gallery="fig-fotoklinis"><img src="./image/klinis/heldi_mata.jpg" class="img-fluid figure-img" data-ref-parent="fig-fotoklinis"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mata-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(h) Sklera ikterik
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-fotoklinis" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-kaki" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-kaki-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./image/klinis/haim_keduakaki.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-9" data-gallery="fig-fotoklinis"><img src="./image/klinis/haim_keduakaki.jpg" class="img-fluid figure-img" data-ref-parent="fig-fotoklinis"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-kaki-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(i) Foto klinis kedua kaki
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fotoklinis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Foto klinis pasien tampak sklera ikterik, ruam malar disertai makula eritema pada beberapa bagian tubuh.
</figcaption>
</figure>
</div>
<p>Pada evaluasi data saat di IGD pasien memiliki skor kriteria klasifikasi SLE dari American College of Rheumatology (ACR)/European League Against Rheumatism (EULAR) 20 poin, dengan rincian lupus kutan akut (+6), keterlibatan sendi (+6), proteinuria (+4) dan thrombositopenia (+4). Pada saat presentasi, pasien menunjukan gejala sesuai dengan SLE aktivitas berat berdasarkan kriteria MEX SLEDAI (tabel <a href="#tbl-mexsledai" class="quarto-xref">1</a>)</p>
<div id="tbl-mexsledai" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mexsledai-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Perkembangan Skor MEX-SLEDAI
</figcaption>
<div aria-describedby="tbl-mexsledai-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th>MEX SLEDAI</th>
<th>7/11/2023</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Proteinuria</td>
<td>+6</td>
</tr>
<tr class="even">
<td>Hemolisis</td>
<td>+3</td>
</tr>
<tr class="odd">
<td>Thrombositopenia</td>
<td>+3</td>
</tr>
<tr class="even">
<td>Arthrtis</td>
<td>+2</td>
</tr>
<tr class="odd">
<td>Ruam Malar</td>
<td>+2</td>
</tr>
<tr class="even">
<td>Total</td>
<td>16</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Pada pemeriksaan penunjang ditemukan beberapa kelainan. Pemeriksaan darah lengkap ditemukan anemia sedang normokromik normositer dan trombositopenia. Pada pemeriksaan kimia klinik ditemukan peningkatan <em>Serum Glutamic Oxaloacetic Transaminase</em> (SGOT), hipoalbuminemia, hipokalemia, alkalosis metabolik (tabel <a href="#tbl-dl" class="quarto-xref">2</a>, <a href="#tbl-kimia" class="quarto-xref">3</a>). Pada pemeriksaan foto thorax anteroposterior tak tampak kelainan pada pulmonum. Pada jantung terukur <em>Cardiothoracic Ratio</em> (CTR) 66 %, dengan <em>splaying carina</em>, apeks mendatar, pinggang jantung melurus, conus pulmonum menonjol sehingga disimpulkan dari foto thorax tampak kesan kardiomegali dengan konfigurasi <em>left ventricular hipertrophy</em> dan <em>left atrial enlargement</em> (gambar <a href="#fig-thorax" class="quarto-xref">3</a>).</p>
<div id="fig-ecgawal" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ecgawal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="image/ecg/heldi_ekg_awal_transform.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-10" data-gallery="quarto-lightbox-gallery-10"><img src="image/ecg/heldi_ekg_awal_transform.jpg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ecgawal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Elektrokardiografi pasien saat masuk rumah sakit (6/11/2023) menunjukan irama atrial fibrilasi.
</figcaption>
</figure>
</div>
<div id="fig-thorax" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-thorax-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="image/thorax_ap.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-11" data-gallery="quarto-lightbox-gallery-11"><img src="image/thorax_ap.jpg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-thorax-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Foto Polos Thorax Anteroposterior (6/11/2023) menunjukan kardiomegali dengan konfigurasi LVH dan LAE serta tak tampak kelainan pada pulmo.
</figcaption>
</figure>
</div>
<div id="tbl-dl" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Data pemeriksaan darah lengkap selama perawatan pasien.
</figcaption>
<div aria-describedby="tbl-dl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Nilai Referensi</th>
<th>6/11/2023</th>
<th>7/11/2023</th>
<th>10/11/2023</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>WBC</td>
<td>4.1 - 11.0 x 10<sup>3</sup>/µL</td>
<td>3.96</td>
<td>11.17</td>
<td>4.42</td>
</tr>
<tr class="even">
<td>Neutrofil (absolut)</td>
<td>2.50 - 7.50 x 10<sup>3</sup>/µL</td>
<td>2.77</td>
<td>9.29</td>
<td>3.41</td>
</tr>
<tr class="odd">
<td>Limfosit (absolut)</td>
<td>1.00 - 4.00 x 10<sup>3</sup>/µL</td>
<td>1.06</td>
<td>1.11</td>
<td>0.76</td>
</tr>
<tr class="even">
<td>Monosit (absolut)</td>
<td>1.00 - 4.00 x 10<sup>3</sup>/µL</td>
<td>0.13</td>
<td>0.77</td>
<td>0.25</td>
</tr>
<tr class="odd">
<td>Eosinofil (absolut)</td>
<td>0.00 - 0.50 x 10<sup>3</sup>/µL</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
</tr>
<tr class="even">
<td>Basofil (absolut)</td>
<td>0.0 - 0.1 x 10<sup>3</sup>/µL</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td>Hemoglobin</td>
<td>12.0 - 16.0 g/dL</td>
<td>7.30</td>
<td>6.90</td>
<td>11.20</td>
</tr>
<tr class="even">
<td>Hematokrit</td>
<td>36.0 - 46.0</td>
<td>23.10</td>
<td>21.50</td>
<td>33.10</td>
</tr>
<tr class="odd">
<td>MCV</td>
<td>80.0 - 100.0 fL</td>
<td>85.90</td>
<td>85.30</td>
<td>82.80</td>
</tr>
<tr class="even">
<td>MCH</td>
<td>26.0 - 34.0 pg</td>
<td>27.10</td>
<td>27.40</td>
<td>28</td>
</tr>
<tr class="odd">
<td>MCHC</td>
<td>31 - 36 g/dL</td>
<td>31.60</td>
<td>32.10</td>
<td>33.80</td>
</tr>
<tr class="even">
<td>Platetet</td>
<td>140 - 440 x 10<sup>3</sup>/µL</td>
<td>67.00</td>
<td>78.00</td>
<td>57</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-kimia" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-kimia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Data pemeriksaan kimia klinik selama perawatan pasien.
</figcaption>
<div aria-describedby="tbl-kimia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Pemeriksaan</th>
<th>Parameter</th>
<th>Referensi</th>
<th>6/11/2023</th>
<th>7/11</th>
<th>12/11</th>
<th>14/11</th>
<th>16/11</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Marker Inflamasi</td>
<td>LED</td>
<td>&lt; 20</td>
<td>69</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Faal Hemostasis</td>
<td>PPT</td>
<td>10 - 12.7</td>
<td>15.9</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>INR</td>
<td>0.9 - 1.1</td>
<td>1.45</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>APTT</td>
<td>23-34.7</td>
<td>28.9</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Fungsi Ginjal</td>
<td>BUN</td>
<td>7.0 - 18.7</td>
<td>7.0</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Kreatinin</td>
<td>0.57 - 1.11</td>
<td>0.51</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>e-LFG</td>
<td>&gt;= 90</td>
<td>135.53</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Elektrolit</td>
<td>Natrium</td>
<td>136 - 145</td>
<td>142</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>Kalium</td>
<td>3.5 - 5.1</td>
<td>2.88</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Kalsium</td>
<td>8.8 - 10.2</td>
<td></td>
<td></td>
<td></td>
<td>7.7 (9.1)</td>
<td></td>
</tr>
<tr class="odd">
<td>Fungsi Liver</td>
<td>AST/SGOT</td>
<td>71</td>
<td>&lt;34</td>
<td></td>
<td></td>
<td>123</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>ALT/SGPT</td>
<td>44</td>
<td>&lt;55</td>
<td></td>
<td></td>
<td>118</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>Albumin</td>
<td>3.4 - 4.8</td>
<td>2.3</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Globulin</td>
<td>2.2 - 3.7</td>
<td>4.10</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>Total Protein</td>
<td>6.4 - 8.3</td>
<td>6.4</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Bilirubin Total</td>
<td>0.2 - 1.2</td>
<td>0.2 - 1.2</td>
<td>4.9</td>
<td>5.60</td>
<td>4.20</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>Bilirubin Direk</td>
<td>0.0 - 0.5</td>
<td>0.0 - 0.5</td>
<td>3.2</td>
<td>3.37</td>
<td>2.13</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Bilirubin Indirek</td>
<td>0.2 - 0.7</td>
<td>0.2 - 0.7</td>
<td>1.70</td>
<td>2.23</td>
<td>2.07</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>Fosfatase Alkali (ALP)</td>
<td>40 - 150</td>
<td></td>
<td>125</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Gamma GT</td>
<td>&lt; 33</td>
<td></td>
<td>232</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Hepatitis Marker</td>
<td>HBsAg</td>
<td>Non reaktif</td>
<td></td>
<td>Non reaktif</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Anti HCV</td>
<td>Non reaktif</td>
<td></td>
<td>Non reaktif</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Analisis Gas Darah</td>
<td>pH</td>
<td>7.35 - 7.45</td>
<td>7.47</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>pCO2</td>
<td>35 - 45</td>
<td>44</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>HCO3-</td>
<td>22 - 26</td>
<td>32</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>BEecf</td>
<td>-2 s.d 2</td>
<td>83</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>pO2</td>
<td>80 - 100%</td>
<td>75</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>SO2c</td>
<td>95 - 100%</td>
<td>96</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>TCO2</td>
<td>24 - 30</td>
<td>33.40</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Coombs Test</td>
<td>Direct Coombs Test</td>
<td>Negatif</td>
<td></td>
<td>Positif</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>Indirect Coombs Test</td>
<td>Negative</td>
<td></td>
<td>Positif</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Imunologi</td>
<td>ANA-IF</td>
<td>&lt; 1:100</td>
<td></td>
<td>1:10.00 (Pola fine Speckled)</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>TrAB (PRODIA)</td>
<td>&lt;= 1.75 IU/L</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>36.3</td>
</tr>
<tr class="even">
<td>Fungsi Tiroid</td>
<td>Free T4</td>
<td>0.7 - 1.48</td>
<td></td>
<td>28</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>TSHs</td>
<td>0.27 - 4.20</td>
<td></td>
<td>&lt; 0.01</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Pemeriksaan elektrokardiografi (EKG) 12 lead saat di IGD menunjukan irama gelombang QRS iregular 140 kali per menit dengan gelombang P yang tidak jelas dan tidak teratur serta tidak sinkron dengan kompleks QRS (gambar <a href="#fig-ecgawal" class="quarto-xref">2</a>). Irama EKG mengesankan sebuah irama fibrilasi atrium dengan respon kontraksi ventrikel cepat (AF RVR). Pemeriksaan ekokardiografi <em>full study</em> 1 hari (7/11/2023) perawatan menunjukan pembesaran atrium derajat berat dengan ukuran ventrikel kiri, ventrikel kanan, serta atrium kanan dalam batas normal. Fungsi sistolik normal dengan ejeksi fraksi 62.6%, namun fungsi diastolik ventrikel kiri belum dapat ditentukan. Terdapat regurgitasi katup mitra pada derajat sedang-berat dicurigai akibat prolapse leaflet mitral anterior. Katup Aorta dan Trikuspid ditemukan mengalami regurgitasi ringan. Tidak ditemukan efusi perikardium. Estimasi tekanan atrium kanan (eRAP) dalam nilai normal (8 mmHg) gambar <a href="#fig-echo" class="quarto-xref">4</a>.</p>
<div id="fig-echo" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-echo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-echo" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-4chamber" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-4chamber-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./image/echo/echo_chamber.png" class="lightbox" data-glightbox="description: .lightbox-desc-12" data-gallery="fig-echo"><img src="./image/echo/echo_chamber.png" class="img-fluid figure-img" data-ref-parent="fig-echo"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-4chamber-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Ekokardiografi tampak ventrikel kiri
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-echo" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-rv" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-rv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./image/echo/echo_rightfunction.png" class="lightbox" data-glightbox="description: .lightbox-desc-13" data-gallery="fig-echo"><img src="./image/echo/echo_rightfunction.png" class="img-fluid figure-img" data-ref-parent="fig-echo"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-rv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Ekokardiografi fungsi jantung kanan
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-echo" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-CW" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-CW-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./image/echo/echo_MR.png" class="lightbox" data-glightbox="description: .lightbox-desc-14" data-gallery="fig-echo"><img src="./image/echo/echo_MR.png" class="img-fluid figure-img" data-ref-parent="fig-echo"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-CW-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Ekokardiografi tampak continous wave doppler pada regurgitasi katup mitral
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-echo" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-PWD" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-PWD-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./image/echo/echo_MR_2.png" class="lightbox" data-glightbox="description: .lightbox-desc-15" data-gallery="fig-echo"><img src="./image/echo/echo_MR_2.png" class="img-fluid figure-img" data-ref-parent="fig-echo"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-PWD-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) Ekokardiografi tampak pulse wave doppler pada regurgitasi katup mitra
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-echo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Ekokardiografi tampak pembesaran atrium kiri disertai regurgitasi katup mitral derajak sedang-berat.
</figcaption>
</figure>
</div>
<p>Pemeriksaan apusan darah tepi menungjukan anemia normokromik, normositer dengan leukositosis dan thrombositopenia. Sebagian besar populasi sel normokromik normositer, anisopoikilositosis (ovalosit, sel tear drop, stomatosit, sel target, sel polikromasia, normoblast. Pada leukosit differential count ditemukan neutrofilia dan tidak ada sel muda. Pada thrombosit tidak ditemukan giant trombosit atau clumping.</p>
<div id="tbl-urin" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-urin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Data pemeriksaan urin selama perawatan pasien.
</figcaption>
<div aria-describedby="tbl-urin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 24%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Pemeriksaan Urin</th>
<th>Parameter</th>
<th>Referensi</th>
<th>7/11/2023</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Urine Lengkap</td>
<td>Berat Jenis</td>
<td>1.003 - 1.035</td>
<td>1.009</td>
</tr>
<tr class="even">
<td></td>
<td>Warna</td>
<td>Kuning</td>
<td>Kuning</td>
</tr>
<tr class="odd">
<td></td>
<td>Kekeruhan</td>
<td></td>
<td>Jernih</td>
</tr>
<tr class="even">
<td></td>
<td>pH</td>
<td>4.5 - 8</td>
<td>7.5</td>
</tr>
<tr class="odd">
<td></td>
<td>Leukosit</td>
<td>Negatif</td>
<td>Negatif</td>
</tr>
<tr class="even">
<td></td>
<td>Nitrit</td>
<td>Negatif</td>
<td>Negatif</td>
</tr>
<tr class="odd">
<td></td>
<td>Protein</td>
<td>Negatif</td>
<td>Negatif</td>
</tr>
<tr class="even">
<td></td>
<td>Glukosa</td>
<td>Negatif</td>
<td>Negatif</td>
</tr>
<tr class="odd">
<td></td>
<td>Keton</td>
<td>Negatif</td>
<td>Negatif</td>
</tr>
<tr class="even">
<td></td>
<td>Darah</td>
<td>Negatif</td>
<td>Negatif</td>
</tr>
<tr class="odd">
<td></td>
<td>Urobilinogen</td>
<td>Normal</td>
<td>Normal</td>
</tr>
<tr class="even">
<td></td>
<td>Bilirubin</td>
<td>Negatif</td>
<td>Negatif</td>
</tr>
<tr class="odd">
<td></td>
<td>Leukosit Sedimen</td>
<td>7 /LPB</td>
<td>5</td>
</tr>
<tr class="even">
<td></td>
<td>Eritrosit Sedimen</td>
<td>5 /LPB</td>
<td>4</td>
</tr>
<tr class="odd">
<td></td>
<td>Sel Epitel Sedimen</td>
<td>8 /LPB</td>
<td>1</td>
</tr>
<tr class="even">
<td></td>
<td>Silinder</td>
<td>2.4 /mikroliter</td>
<td>0.14</td>
</tr>
<tr class="odd">
<td></td>
<td>Bakteri</td>
<td>130.7</td>
<td>1993.8</td>
</tr>
<tr class="even">
<td>Rasio Protein kreatinin urin</td>
<td>Mikro Total protein urin</td>
<td>1 - 14 mg/dl</td>
<td>24.10</td>
</tr>
<tr class="odd">
<td></td>
<td>Kreatinin urin</td>
<td>63 - 166</td>
<td>2.41</td>
</tr>
<tr class="even">
<td></td>
<td>Rasio protein kreatinin</td>
<td>2.41</td>
<td>&lt; 0.2</td>
</tr>
<tr class="odd">
<td>Tes Kehamilan (RS Perujuk)</td>
<td></td>
<td>Negatif</td>
<td>Negatif</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-kalium" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-kalium-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Data pemantauan kalium selama perawatan pasien.
</figcaption>
<div aria-describedby="tbl-kalium-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th>Tangal pemeriksaan</th>
<th>Kalium</th>
<th>Koreksi Kalium</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>6/11/2023</td>
<td>2.88</td>
<td>Drip KCL 50 Meq</td>
</tr>
<tr class="even">
<td>8/11/2023</td>
<td>2.95</td>
<td>Drip KCL 25 Meq</td>
</tr>
<tr class="odd">
<td>8/11/2023</td>
<td>2.45</td>
<td>Drip KCL 50 Meq</td>
</tr>
<tr class="even">
<td>9/11/2023</td>
<td>3.91</td>
<td></td>
</tr>
<tr class="odd">
<td>15/11/2023</td>
<td>2.25</td>
<td>Drip KCL 50 Meq</td>
</tr>
<tr class="even">
<td>16/11/2023</td>
<td>3.18</td>
<td>KSR 500 mg tiap 12 jam per oral (Selanjutnya Rawat Jalan)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Diagnosis kerja pasien meliputi, SLE derajat aktivitas berat dengan anemia sedang normokromik normositer et causa anemia hemolitik, susp kardiomiopati lupus, atrial fibrilasi rapid ventricular response, diare akut ec susp viral dengan dehidrasi ringan-sedang, hipokalemia et causa suspect loss. Pada pasien diberikan terapi pulsedose metil prednisolon 500 mg dalam NaCl 0.9% 100 cc intravena habis dalam 30 menit selama 3 hari. Terapi supportif lain meliputi omeprazole 40 mg sebelum pemberian pulse dose metilprednisolon, kandesartan 8 mg tiap 24 jam per oral, oralit ad libitum, drip KCL 50 meq dalam NaCl 0.9% 500 cc habis dalam 8 jam dan transfusi <em>packed red cell</em> dengan target hemoglobin &gt; 10 g/dL. Pasien dikonsulkan ke divisi kardiologi terkait atrial fibrilasi dan diberikan terapi digoxin 0.5 mg bolus pelan jika denyut jantung &gt; 110.</p>
<p>Terkait dengan atrial fibrilasi, pada pasien dilakukan pemeriksaan FT4 dan TSH untuk evaluasi penyebab atrial fibrilasi. Evaluasi paska pemeriksaan FT4 dan TSH yang menunjukan kondisi hipertiroid dicurigai akibat penyakit graves (skor Wayne 20, tabel <a href="#tbl-wayne" class="quarto-xref">6</a>) disertai gejala klinis sesuai dengan kondisi badai tiroid (thyroid storm) dengan skor Burch Wartofsky 50 poin (tabel <a href="#tbl-bw" class="quarto-xref">7</a>). Terapi diberikan meliputi propanolol 60 mg tiap 6 jam per oral, propiltiourasil (PTU) 600 mg sebagai dosis awal (<em>loading dose)</em> dilanjutkan 300 mg tiap 6 jam per oral, steroid dengan metilprednisolon sesuai dosis untuk SLE, serta larutan iodin 5 tetes setiap 8 jam per oral setelah pemberian PTU jika obat tersedia.</p>
<p>Terapi atrial fibrilasi dari kardiologi meliputi digoksin 0.5 mg intravena jika laju denyut jantung &gt; 110 kali per menit. Pada pasien didapatkan kondisi hipertensi dengan terapi ramipril 5 mg tiap 12 jam per oral serta nifedipin (lepas lambat) 30 mg tiap 24 jam per oral.</p>
<div id="tbl-wayne" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-wayne-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Penilaian gejala dan tanda klinis hipertiroid dengan skor Wayne
</figcaption>
<div aria-describedby="tbl-wayne-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Gejala onset baru atau memberat</th>
<th>Skor</th>
<th>Nilai</th>
<th>Tanda</th>
<th>Skor jika ada</th>
<th>Skor jika tidak ada</th>
<th>Nilai</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dyspnea on effect</td>
<td>+1</td>
<td>0</td>
<td>Palpable thyroid</td>
<td>+3</td>
<td>-3</td>
<td>+3</td>
</tr>
<tr class="even">
<td>Palpitations</td>
<td>+2</td>
<td>+2</td>
<td>Bruit over thyroid</td>
<td>+2</td>
<td>-2</td>
<td>-2</td>
</tr>
<tr class="odd">
<td>Tiredness</td>
<td>+2</td>
<td>+2</td>
<td>Exopthalmoses</td>
<td>+2</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Preference for heat</td>
<td>-5</td>
<td>0</td>
<td>Lid retraction</td>
<td>+2</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Preference for cold</td>
<td>+5</td>
<td>+5</td>
<td>Lid lag</td>
<td>+1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Excessive sweating</td>
<td>+3</td>
<td>0</td>
<td>Hyperkinesis</td>
<td>+4</td>
<td>-2</td>
<td>-2</td>
</tr>
<tr class="odd">
<td>Nervousness</td>
<td>+2</td>
<td>+2</td>
<td>Hands hot</td>
<td>+2</td>
<td>-2</td>
<td>-2</td>
</tr>
<tr class="even">
<td>Appetite: increased</td>
<td>+3</td>
<td>+3</td>
<td>Hands moist</td>
<td>+1</td>
<td>-1</td>
<td>-1</td>
</tr>
<tr class="odd">
<td>Appetite: decreased</td>
<td>-3</td>
<td>0</td>
<td>Casual pulse rate</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Weight: increased</td>
<td>-3</td>
<td>0</td>
<td>&gt;80/min</td>
<td>0</td>
<td>-3</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Weight: decreased</td>
<td>+3</td>
<td>+3</td>
<td>&gt;90/min</td>
<td>+3</td>
<td>0</td>
<td>+3</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td>Atrial fibrilation</td>
<td>+4</td>
<td>0</td>
<td>+4</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-bw" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-bw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Penilaian derajat gejala hipertiroid dengan skor Burch-Wartofsky
</figcaption>
<div aria-describedby="tbl-bw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Burch Wartofsky Score</th>
<th>7/11/2023 - 9/11/2023</th>
<th>10/11/24 - 12/11/24</th>
<th>13/11/24 - 14/11/24</th>
<th>15/11/24</th>
<th>16/11/24</th>
<th>17/11/24</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Temperatur</td>
<td>&lt; 37.2 (0)</td>
<td>&lt; 37.2 (0)</td>
<td>&lt; 37.2 (0)</td>
<td>&lt; 37.2 (0)</td>
<td>&lt; 37.2 (0)</td>
<td>&lt; 37.2 (0)</td>
</tr>
<tr class="even">
<td>Disfungsi Sistem Saraf Pusat</td>
<td>tidak ada (0)</td>
<td>tidak ada (0)</td>
<td>tidak ada (0)</td>
<td>tidak ada (0)</td>
<td>tidak ada (0)</td>
<td>tidak ada (0)</td>
</tr>
<tr class="odd">
<td>Disfungsi Gastrointestinal-hepar</td>
<td>Berat-jaundice tidak dapat dijelaskan (+20)</td>
<td>Berat-jaundice tidak dapat dijelaskan (+20)</td>
<td>Keluhan membaik (0)</td>
<td>Keluhan membaik (0)</td>
<td>Keluhan membaik (0)</td>
<td>Keluhan membaik (0)</td>
</tr>
<tr class="even">
<td>Denyut jantung</td>
<td>110 - 199 (+10)</td>
<td>90 - 109 (+5)</td>
<td>90 - 109 (+5)</td>
<td>&gt;= 140(+25)</td>
<td>&gt;=120 -129 (+15)</td>
<td>&gt;=90 -109 (+5)</td>
</tr>
<tr class="odd">
<td>Kondisi Gagal jantung Kongestif</td>
<td>tidak ada (0)</td>
<td>tidak ada (0)</td>
<td>tidak ada (0)</td>
<td>tidak ada (0)</td>
<td>tidak ada (0)</td>
<td>tidak ada (0)</td>
</tr>
<tr class="even">
<td>Atrial Fibrilasi</td>
<td>Ada (+10)</td>
<td>tidak (0)</td>
<td>ada (10)</td>
<td>ada (10)</td>
<td>ada (10)</td>
<td>ada (10)</td>
</tr>
<tr class="odd">
<td>Faktor Presipitasi</td>
<td>Ada (+10)</td>
<td>Ada (+10)</td>
<td>tidak (0)</td>
<td>tidak (0)</td>
<td>tidak (0)</td>
<td>tidak (0)</td>
</tr>
<tr class="even">
<td>Total</td>
<td>50 (<em>Highly suggestive of thyroid storm</em>)</td>
<td>35 (<em>Suggestive of impending thyroid storm</em>)</td>
<td>15 (<em>Unlikely to represent thyroid storm</em>)</td>
<td>35 (<em>Suggestive of impending thyroid storm</em>)</td>
<td>25 (<em>Suggestive of impending thyroid storm</em>)</td>
<td>15 (<em>Unlikely to represent thyroid storm</em>)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Pada pemeriksaan ultrasonografi Tiroid ditemukan peningkatan vaskularisasi pada parenkim tiroid kanan, kiri dan istmus. Pada pemeriksaan tidak ditemukan massa/nodul/kista pada kelenjar tiroid, namun tampak pembesaran kelenjar getah bening pada regio colli kiri, submandibula kanan-kiri, preaurikula kanan dan parotid kiri. Kelenjar parotis kanan tak tampak kelainan. Pemeriksaan USG ini mendukung <em>Graves Disease</em> dengan multipel <em>non suspicious</em> limfadenopati pada regio colli kiri, submandibula kanan-kiri, preauricula kanan, dan parotid kiri (gambar <a href="#fig-usgtiroid" class="quarto-xref">5</a>). Temuan USG tiroid ini mendukung temuan klinis serta laboratorium untuk penyakit Graves. Penegakan diagnosis pada tahap akhir membutuhkan pemeriksaan Tiroid Receptor Antibody (TRAb) namun kendala teknis laboratorium rumah sakit yang belum mampu melakukan pemeriksaan tersebut. Pemeriksaan TRAb dilakukan pada akhir perawatan dengan hasil nilai serum yang diatas batas normal (36.3 IU/L).</p>
<div id="fig-usgtiroid" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-usgtiroid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-usgtiroid" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-Rtiroid" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-Rtiroid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./image/usg_tiroid/tiroid_RLobe.png" class="lightbox" data-glightbox="description: .lightbox-desc-16" data-gallery="fig-usgtiroid"><img src="./image/usg_tiroid/tiroid_RLobe.png" class="img-fluid figure-img" data-ref-parent="fig-usgtiroid"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-Rtiroid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) USG Tiroid Lobus Kanan
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-usgtiroid" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-Istmus" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-Istmus-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./image/usg_tiroid/tiroid_istmus.png" class="lightbox" data-glightbox="description: .lightbox-desc-17" data-gallery="fig-usgtiroid"><img src="./image/usg_tiroid/tiroid_istmus.png" class="img-fluid figure-img" data-ref-parent="fig-usgtiroid"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-Istmus-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) USG Tiroid Istmus
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-usgtiroid" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-Ltiroid" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-Ltiroid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./image/usg_tiroid/tiroid_LLobe.png" class="lightbox" data-glightbox="description: .lightbox-desc-18" data-gallery="fig-usgtiroid"><img src="./image/usg_tiroid/tiroid_LLobe.png" class="img-fluid figure-img" data-ref-parent="fig-usgtiroid"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-Ltiroid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) USG Tiroid Lobus Kiri
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-usgtiroid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Ultrasonografi kelenjar tiroid tampak pembesaran ukuran kelenjar, hipoekoik diffuse disertai tampak peningkatakan vaskularisasi pada pencitraan dopler.
</figcaption>
</figure>
</div>
<p>Pada pemeriksaan ultrasonografi abdomen ditemukan nodul tunggal hipoechoic dengan hiperechoic di tepinya dan internal echo didalamnya, berbatas tegas tepi regular pada segmen VIII hepar, terukur +/- 1.8 x 1.7 cm yang pada CDUS tampak vaskularisasi pada tepinya. Pada pencitraan cavum pelvis, ditemukan cairan bebas minimal. Tindakan diagnostik lanjutan terkait temuan nodul hepar terbatas pada pemeriksaan USG abdomen. Terapi terkait transaminitis disertai peningkatan bilirubin diberikan berupa terapi supportif berupa curcuma tablet tiap 8 jam per oral serta asam ursodioksikolat 250 mg tiap 8 jam per oral. Pada akhir masa perawatan rumah sakit pemeriksaan bilirubin diulang dan hasilnya menunjukan penurunan kadar bilirubin.</p>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><a href="image/usg_abd/abd_nodul.png" class="lightbox" data-glightbox="description: .lightbox-desc-19" data-gallery="quarto-lightbox-gallery-19" title="USG abdomen (9/11/2023) ditemukan liver tidak membesar, permukaan licin, sudut tajam, tepi rata, sistem vasculer dan bilier tampak normal, echoparenchym normal, tampak single nodul hipoechoic dengan hiperechoic di tepinya dan internal echo didalamnya, berbatas tegas tepi regular pada segmen VIII hepar, terukur +/- 1.8 x 1.7 cm yang pada CDUS tampak vaskularisasi pada tepinya."><img src="image/usg_abd/abd_nodul.png" class="img-fluid quarto-figure quarto-figure-left figure-img" alt="USG abdomen (9/11/2023) ditemukan liver tidak membesar, permukaan licin, sudut tajam, tepi rata, sistem vasculer dan bilier tampak normal, echoparenchym normal, tampak single nodul hipoechoic dengan hiperechoic di tepinya dan internal echo didalamnya, berbatas tegas tepi regular pada segmen VIII hepar, terukur +/- 1.8 x 1.7 cm yang pada CDUS tampak vaskularisasi pada tepinya."></a></p>
</figure>
</div>
<figcaption>USG abdomen (9/11/2023) ditemukan liver tidak membesar, permukaan licin, sudut tajam, tepi rata, sistem vasculer dan bilier tampak normal, echoparenchym normal, tampak single nodul hipoechoic dengan hiperechoic di tepinya dan internal echo didalamnya, berbatas tegas tepi regular pada segmen VIII hepar, terukur +/- 1.8 x 1.7 cm yang pada CDUS tampak vaskularisasi pada tepinya.</figcaption>
</figure>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="index_files/figure-html/timeline_Graves-1.png" class="lightbox" data-glightbox="description: .lightbox-desc-20" data-gallery="quarto-lightbox-gallery-20" title="Perubahan dosis obat menyesuaikan klinis hipertiroid"><img src="index_files/figure-html/timeline_Graves-1.png" class="img-fluid figure-img" width="576" alt="Perubahan dosis obat menyesuaikan klinis hipertiroid"></a></p>
<figcaption>Perubahan dosis obat menyesuaikan klinis hipertiroid</figcaption>
</figure>
</div>
</div>
<a class="quarto-notebook-link" id="nblink-1" href="index-preview.html">Source: Article Notebook</a></div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="index_files/figure-html/timeline_SLE-1.png" class="lightbox" data-glightbox="description: .lightbox-desc-21" data-gallery="quarto-lightbox-gallery-21" title="Perubahan dosis obat imunosupresan untuk penyakit SLE"><img src="index_files/figure-html/timeline_SLE-1.png" class="img-fluid figure-img" width="576" alt="Perubahan dosis obat imunosupresan untuk penyakit SLE"></a></p>
<figcaption>Perubahan dosis obat imunosupresan untuk penyakit SLE</figcaption>
</figure>
</div>
</div>
<a class="quarto-notebook-link" id="nblink-2" href="index-preview.html">Source: Article Notebook</a></div>
</section>
<section id="diskusi" class="level2">
<h2 class="anchored" data-anchor-id="diskusi">Diskusi</h2>
<p>Penelitian terbaru oleh Xian et al menemukan bahwa SLE meningkatkan risiko penyaki graves (OR=1.13, 95% CI 1.05-1.22, p =0.003), dan berlaku juga sebaliknya penyakit graves meningkatkan risiko SLE (OR=1.27, 95% CI 1.09-1.48, p =0.018).<span class="citation" data-cites="xian2024"><sup><a href="#ref-xian2024" role="doc-biblioref">1</a></sup></span> Hubungan sebab akibat antara penyakit graves dan SLE yang ditemukan dalam penelitian tersebut semakin menegaskan temuan epidemiologi sebelumnya. Patogenesis SLE dan penyakit graves mungkin dipengaruhi oleh mutasi pada gen HLA. Sebuah meta-analisis yang dilakukan sebelumnya menemukan bahwa mutasi pada HLA-DR3 dan HLA-DR15 secara signifikan meningkatkan kemungkinan SLE.<span class="citation" data-cites="xue_2018"><sup><a href="#ref-xue_2018" role="doc-biblioref">6</a></sup></span> Kehadiran gen HLA yang bermutasi dapat mengakibatkan perubahan kompleks HLA pada sel penyaji antigen, sehingga mempengaruhi interaksi antara sel B dan T. Situasi ini dapat menyebabkan disregulasi sel B yang reaktif terhadap diri sendiri dan produksi autoantibodi, yang dapat berfungsi sebagai mediator efek kausal SLE pada penyakit graves.<span class="citation" data-cites="xian2024"><sup><a href="#ref-xian2024" role="doc-biblioref">1</a></sup></span></p>
<p>Selain gen terkait HLA, gen non-HLA juga diduga memainkan peran penting dalam interaksi antara SLE dan penyakit graves. Protein terkait limfosit T sitotoksik 4 (CTLA-4) adalah reseptor protein yang berfungsi sebagai cek poin pemeriksaan imun untuk menurunkan regulasi respons imun dengan mengikat ligan CD80 dan CD86 pada permukaan sel penyaji antigen, sehingga mengatur aktivasi sel T dan proliferasinya.<span class="citation" data-cites="syn2017"><sup><a href="#ref-syn2017" role="doc-biblioref">7</a></sup></span> Mutasi pada gen CTLA-4 telah dikaitkan dengan SLE dan penyakit graves. Sebuah meta-analisis menunjukkan bahwa polimorfisme gen CTLA-4 pada populasi Asia dikaitkan dengan risiko SLE.<span class="citation" data-cites="zhai2013"><sup><a href="#ref-zhai2013" role="doc-biblioref">8</a></sup></span> Sebuah studi oleh Lee dkk. menemukan bahwa beberapa polimorfisme nukleotida tunggal CTLA-4 dikaitkan dengan penyakit graves dan penyakit tiroid autoimun seperti tiroiditis Hashimoto.<span class="citation" data-cites="lee2015"><sup><a href="#ref-lee2015" role="doc-biblioref">9</a></sup></span> Mutasi pada gen CTLA-4 dapat menyebabkan defisiensi regulasi penurunan regulasi respon imun sel T, yang mengakibatkan hiperaktivasi sel T dan dengan demikian memicu penyakit autoimun. Faktor ini mungkin juga memainkan peran mediasi dalam hubungan antara penyakit graves dan SLE.<span class="citation" data-cites="xian2024"><sup><a href="#ref-xian2024" role="doc-biblioref">1</a></sup></span></p>
<p>SLE dan penyakit graves ditandai oleh kelainan regulasi imun yang mungkin berhubungan erat dengan interferon tipe I (IFN-I).<span class="citation" data-cites="pan2019"><sup><a href="#ref-pan2019" role="doc-biblioref">10</a></sup></span> Interferon tipe I, termasuk IFN-a, IFN-b, IFN-ϵ, IFN-k, dll., adalah sitokin yang memainkan peran penting dalam peradangan, regulasi kekebalan, pengenalan sel tumor, dan respons sel T. Dalam konteks penyakit autoimun, IFN-I dapat berkontribusi pada perkembangan SLE dengan meningkatkan presentasi antigen dan respon limfosit serta menginduksi ekspresi kemokin. IFN-I meningkatkan aktivasi sel B, diferensiasi, proliferasi dan produksi antibodi, dan dapat menginduksi ekspresi reseptor <em>Thyroid-timulating hormone</em>.<span class="citation" data-cites="ivashkiv2013"><sup><a href="#ref-ivashkiv2013" role="doc-biblioref">11</a></sup></span> Dengan demikian, hal ini mungkin berdampak pada menignkatnya risiko penyakit graves.</p>
<p>Selain regulasi imun yang menyimpang, SLE dan penyakit graves mungkin memiliki patogenesis yang sama terkait autoantibodi yang menyebabkan kerusakan jaringan. Sebuah meta-analisis yang dilakukan oleh Pan et al.&nbsp;menunjukkan bahwa kadar antibodi tiroid peroksidase (TPOAb) dan antibodi tiroglobulin (TgAb) jauh lebih tinggi pada pasien SLE dibandingkan dengan populasi sehat, yang menunjukkan adanya korelasi antara SLE dan penyakit tiroid autoimun.<span class="citation" data-cites="pan2015"><sup><a href="#ref-pan2015" role="doc-biblioref">12</a></sup></span> Penelitian yang dilakukan oleh Lanzolla dkk. menunjukkan bahwa keberadaan antibodi antinuklear diamati pada sekitar 80% pasien yang didiagnosis dengan penyakit graves. Temuan ini menunjukkan bahwa penyakit graves berpotensi mempengaruhi perkembangan SLE melalui jalur autoantibodi.<span class="citation" data-cites="lanzolla2022"><sup><a href="#ref-lanzolla2022" role="doc-biblioref">13</a></sup></span></p>
<p>Jalur imunologi yang sama dalam perkembangan SLE dan penyakit graves ditunjukkan oleh adanya tumpang tindih kemokin dan sitokin spesifik. Penelitian terbaru berfokus pada interaksi antara CXCL10 dan CXCR3 dalam respon imun T helper 1 sangat penting dalam etiologi penyakit graves dan SLE.<span class="citation" data-cites="antonelli2014 antonelli2020"><sup><a href="#ref-antonelli2014" role="doc-biblioref">14</a>,<a href="#ref-antonelli2020" role="doc-biblioref">15</a></sup></span> Selain itu, dilaporkan bahwa peningkatan kadar IL-37 berkorelasi positif dengan konsentrasi TRAb dan derajat aktivitas SLE, sehingga ini menunjukkan bahwa IL-37 memainkan peran penting dalam terjadinya penyakit graves dan SLE.<span class="citation" data-cites="xu2015"><sup><a href="#ref-xu2015" role="doc-biblioref">16</a></sup></span></p>
</section>
<section id="ringkasan" class="level2">
<h2 class="anchored" data-anchor-id="ringkasan">Ringkasan</h2>
<p>Penyakit Graves secara genetik diprediksi meningkatkan risiko SLE, dan berlaku juga sebaliknya. Laporan kasus ini diharapkan dapat memberikan dasar baru untuk skrining dan tatalaksana pasien dengan penyakit graves yang memiliki gejala baru yang tidak spesifik harus diskrining untuk SLE sehingga memfasilitasi diagnosis dan pengobatan tepat waktu dan menghindari penundaan atau eksaserbasi penyakit. Pada saat yang sama, fungsi tiroid juga perlu dipantau selama penatalaksanaan pasien SLE, sehingga dapat menyesuaikan rencana pengobatan dan meningkatkan kualitas hidup pasien.</p>
</section>
<section id="daftar-pustaka" class="level2">
<h2 class="anchored" data-anchor-id="daftar-pustaka">Daftar Pustaka</h2>
<div class="hidden" aria-hidden="true">
<span class="glightbox-desc lightbox-desc-1">Figure&nbsp;1&nbsp;(a): Ruam pada belakang telinga kiri</span>
<span class="glightbox-desc lightbox-desc-2">Figure&nbsp;1&nbsp;(b): Foto klinis wajah</span>
<span class="glightbox-desc lightbox-desc-3">Figure&nbsp;1&nbsp;(c): Ruam pada belakang telinga kanan</span>
<span class="glightbox-desc lightbox-desc-4">Figure&nbsp;1&nbsp;(d): Foto klinis leher kanan</span>
<span class="glightbox-desc lightbox-desc-5">Figure&nbsp;1&nbsp;(e): Foto klinis leher depan</span>
<span class="glightbox-desc lightbox-desc-6">Figure&nbsp;1&nbsp;(f): Foto klinis leher kiri</span>
<span class="glightbox-desc lightbox-desc-7">Figure&nbsp;1&nbsp;(g): Foto klinis kedua tangan</span>
<span class="glightbox-desc lightbox-desc-8">Figure&nbsp;1&nbsp;(h): Sklera ikterik</span>
<span class="glightbox-desc lightbox-desc-9">Figure&nbsp;1&nbsp;(i): Foto klinis kedua kaki</span>
<span class="glightbox-desc lightbox-desc-10">Figure&nbsp;2: Elektrokardiografi pasien saat masuk rumah sakit (6/11/2023) menunjukan irama atrial fibrilasi.</span>
<span class="glightbox-desc lightbox-desc-11">Figure&nbsp;3: Foto Polos Thorax Anteroposterior (6/11/2023) menunjukan kardiomegali dengan konfigurasi LVH dan LAE serta tak tampak kelainan pada pulmo.</span>
<span class="glightbox-desc lightbox-desc-12">Figure&nbsp;4&nbsp;(a): Ekokardiografi tampak ventrikel kiri</span>
<span class="glightbox-desc lightbox-desc-13">Figure&nbsp;4&nbsp;(b): Ekokardiografi fungsi jantung kanan</span>
<span class="glightbox-desc lightbox-desc-14">Figure&nbsp;4&nbsp;(c): Ekokardiografi tampak continous wave doppler pada regurgitasi katup mitral</span>
<span class="glightbox-desc lightbox-desc-15">Figure&nbsp;4&nbsp;(d): Ekokardiografi tampak pulse wave doppler pada regurgitasi katup mitra</span>
<span class="glightbox-desc lightbox-desc-16">Figure&nbsp;5&nbsp;(a): USG Tiroid Lobus Kanan</span>
<span class="glightbox-desc lightbox-desc-17">Figure&nbsp;5&nbsp;(b): USG Tiroid Istmus</span>
<span class="glightbox-desc lightbox-desc-18">Figure&nbsp;5&nbsp;(c): USG Tiroid Lobus Kiri</span>
<span class="glightbox-desc lightbox-desc-19">USG abdomen (9/11/2023) ditemukan liver tidak membesar, permukaan licin, sudut tajam, tepi rata, sistem vasculer dan bilier tampak normal, echoparenchym normal, tampak single nodul hipoechoic dengan hiperechoic di tepinya dan internal echo didalamnya, berbatas tegas tepi regular pada segmen VIII hepar, terukur +/- 1.8 x 1.7 cm yang pada CDUS tampak vaskularisasi pada tepinya.</span>
<span class="glightbox-desc lightbox-desc-20">Perubahan dosis obat menyesuaikan klinis hipertiroid</span>
<span class="glightbox-desc lightbox-desc-21">Perubahan dosis obat imunosupresan untuk penyakit SLE</span>
</div>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body" role="list">
<div id="ref-xian2024" class="csl-entry" role="listitem">
<div class="csl-left-margin">1. </div><div class="csl-right-inline">Xian W, Liu B, Li J, Yang Y, Hong S, Xiao H, et al. Graves<span>’</span> disease and systemic lupus erythematosus: A mendelian randomization study. Frontiers in Immunology. 2024;15. Diakses pada: <a href="http://dx.doi.org/10.3389/fimmu.2024.1273358">http://dx.doi.org/10.3389/fimmu.2024.1273358</a></div>
</div>
<div id="ref-smith2016" class="csl-entry" role="listitem">
<div class="csl-left-margin">2. </div><div class="csl-right-inline">Smith TJ, Hegedüs L. Graves<span>’</span> Disease. Longo DL, editor. New England Journal of Medicine. 2016;375(16):1552–65. Diakses pada: <a href="http://dx.doi.org/10.1056/NEJMra1510030">http://dx.doi.org/10.1056/NEJMra1510030</a></div>
</div>
<div id="ref-davies2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">3. </div><div class="csl-right-inline">Davies TF, Andersen S, Latif R, Nagayama Y, Barbesino G, Brito M, et al. Graves<span>’</span> disease. Nature Reviews Disease Primers. 2020;6(1). Diakses pada: <a href="http://dx.doi.org/10.1038/s41572-020-0184-y">http://dx.doi.org/10.1038/s41572-020-0184-y</a></div>
</div>
<div id="ref-ferrari2019" class="csl-entry" role="listitem">
<div class="csl-left-margin">4. </div><div class="csl-right-inline">Ferrari SM, Fallahi P, Ruffilli I, Elia G, Ragusa F, Benvenga S, et al. The association of other autoimmune diseases in patients with Graves’ disease (with or without ophthalmopathy): Review of the literature and report of a large series. Autoimmunity Reviews. 2019;18(3):287–92. Diakses pada: <a href="http://dx.doi.org/10.1016/j.autrev.2018.10.001">http://dx.doi.org/10.1016/j.autrev.2018.10.001</a></div>
</div>
<div id="ref-lee2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">5. </div><div class="csl-right-inline">Lee C, Chen S-F, Yang Y-C, Hsu CY, Shen Y-C. Association between Graves’ disease and risk of incident systemic lupus erythematosus: A nationwide population<span>-</span>based cohort study. International Journal of Rheumatic Diseases. 2020;24(2):240–5. Diakses pada: <a href="http://dx.doi.org/10.1111/1756-185x.14027">http://dx.doi.org/10.1111/1756-185x.14027</a></div>
</div>
<div id="ref-xue_2018" class="csl-entry" role="listitem">
<div class="csl-left-margin">6. </div><div class="csl-right-inline">Xue K, Niu W-Q, Cui Y. <a href="https://doi.org/10.4103/0366-6999.246058">Association of <span>HLA</span>-<span>DR3</span> and <span>HLA</span>-<span>DR15</span> <span>Polymorphisms</span> with <span>Risk</span> of <span>Systemic</span> <span>Lupus</span> <span>Erythematosus</span>.</a> Chinese medical journal. 2018;131(23):2844–51. </div>
</div>
<div id="ref-syn2017" class="csl-entry" role="listitem">
<div class="csl-left-margin">7. </div><div class="csl-right-inline">Syn NL, Teng MWL, Mok TSK, Soo RA. De-novo and acquired resistance to immune checkpoint targeting. The Lancet Oncology. 2017;18(12):e731–41. Diakses pada: <a href="http://dx.doi.org/10.1016/s1470-2045(17)30607-1">http://dx.doi.org/10.1016/s1470-2045(17)30607-1</a></div>
</div>
<div id="ref-zhai2013" class="csl-entry" role="listitem">
<div class="csl-left-margin">8. </div><div class="csl-right-inline">Zhai J-X, Zou L-W, Zhang Z-X, Fan W-J, Wang H-Y, Liu T, et al. CTLA-4 polymorphisms and systemic lupus erythematosus (SLE): a meta-analysis. Molecular Biology Reports. 2013;40(9):5213–23. Diakses pada: <a href="http://dx.doi.org/10.1007/s11033-012-2125-7">http://dx.doi.org/10.1007/s11033-012-2125-7</a></div>
</div>
<div id="ref-lee2015" class="csl-entry" role="listitem">
<div class="csl-left-margin">9. </div><div class="csl-right-inline">Lee HJ, Li CW, Hammerstad SS, Stefan M, Tomer Y. Immunogenetics of autoimmune thyroid diseases: A comprehensive review. Journal of Autoimmunity. 2015;64:82–90. Diakses pada: <a href="http://dx.doi.org/10.1016/j.jaut.2015.07.009">http://dx.doi.org/10.1016/j.jaut.2015.07.009</a></div>
</div>
<div id="ref-pan2019" class="csl-entry" role="listitem">
<div class="csl-left-margin">10. </div><div class="csl-right-inline">Pan L, Lu M-P, Wang J-H, Xu M, Yang S-R. Immunological pathogenesis and treatment of systemic lupus erythematosus. World Journal of Pediatrics. 2019;16(1):19–30. Diakses pada: <a href="http://dx.doi.org/10.1007/s12519-019-00229-3">http://dx.doi.org/10.1007/s12519-019-00229-3</a></div>
</div>
<div id="ref-ivashkiv2013" class="csl-entry" role="listitem">
<div class="csl-left-margin">11. </div><div class="csl-right-inline">Ivashkiv LB, Donlin LT. Regulation of type I interferon responses. Nature Reviews Immunology. 2013;14(1):36–49. Diakses pada: <a href="http://dx.doi.org/10.1038/nri3581">http://dx.doi.org/10.1038/nri3581</a></div>
</div>
<div id="ref-pan2015" class="csl-entry" role="listitem">
<div class="csl-left-margin">12. </div><div class="csl-right-inline">Pan X-F, Gu J-Q, Shan Z-Y. Patients with Systemic Lupus Erythematosus Have Higher Prevalence of Thyroid Autoantibodies: A Systematic Review and Meta-Analysis. Assassi S, editor. PLOS ONE. 2015;10(4):e0123291. Diakses pada: <a href="http://dx.doi.org/10.1371/journal.pone.0123291">http://dx.doi.org/10.1371/journal.pone.0123291</a></div>
</div>
<div id="ref-lanzolla2022" class="csl-entry" role="listitem">
<div class="csl-left-margin">13. </div><div class="csl-right-inline">Lanzolla G, Puccinelli L, Giudetti M, Comi S, Menconi F, Maglionico MN, et al. Anti-nuclear autoantibodies in Graves<span>’</span> disease and Graves<span>’</span> orbitopathy. Journal of Endocrinological Investigation. 2022;46(2):337–44. Diakses pada: <a href="http://dx.doi.org/10.1007/s40618-022-01906-3">http://dx.doi.org/10.1007/s40618-022-01906-3</a></div>
</div>
<div id="ref-antonelli2014" class="csl-entry" role="listitem">
<div class="csl-left-margin">14. </div><div class="csl-right-inline">Antonelli A, Ferrari SM, Giuggioli D, Ferrannini E, Ferri C, Fallahi P. Chemokine (C<span></span>X<span></span>C motif) ligand (CXCL)10 in autoimmune diseases. Autoimmunity Reviews. 2014;13(3):272–80. Diakses pada: <a href="http://dx.doi.org/10.1016/j.autrev.2013.10.010">http://dx.doi.org/10.1016/j.autrev.2013.10.010</a></div>
</div>
<div id="ref-antonelli2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">15. </div><div class="csl-right-inline">Antonelli A, Fallahi P, Elia G, Ragusa F, Paparo SR, Ruffilli I, et al. Graves’ disease: Clinical manifestations, immune pathogenesis (cytokines and chemokines) and therapy. Best Practice &amp; Research Clinical Endocrinology &amp; Metabolism. 2020;34(1):101388. Diakses pada: <a href="http://dx.doi.org/10.1016/j.beem.2020.101388">http://dx.doi.org/10.1016/j.beem.2020.101388</a></div>
</div>
<div id="ref-xu2015" class="csl-entry" role="listitem">
<div class="csl-left-margin">16. </div><div class="csl-right-inline">Xu W-D, Zhao Y, Liu Y. Insights into IL-37, the role in autoimmune diseases. Autoimmunity Reviews. 2015;14(12):1170–5. Diakses pada: <a href="http://dx.doi.org/10.1016/j.autrev.2015.08.006">http://dx.doi.org/10.1016/j.autrev.2015.08.006</a></div>
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"openEffect":"zoom","closeEffect":"zoom","descPosition":"bottom","selector":".lightbox","loop":false});
window.onload = () => {
  lightboxQuarto.on('slide_before_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    const href = trigger.getAttribute('href');
    if (href !== null) {
      const imgEl = window.document.querySelector(`a[href="${href}"] img`);
      if (imgEl !== null) {
        const srcAttr = imgEl.getAttribute("src");
        if (srcAttr && srcAttr.startsWith("data:")) {
          slideConfig.href = srcAttr;
        }
      }
    } 
  });

  lightboxQuarto.on('slide_after_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    if (window.Quarto?.typesetMath) {
      window.Quarto.typesetMath(slideNode);
    }
  });

};
          </script>




</body></html>